package com.google.android.gms.ads.internal.f;

import android.content.Context;
import android.content.SharedPreferences;
import android.content.SharedPreferences.Editor;
import com.google.android.gms.ads.internal.client.u;
import com.google.android.gms.ads.internal.q.a.a;
import com.google.android.gms.ads.internal.util.bo;
import com.google.android.gms.ads.internal.util.client.k;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;

@a
public final class n
{
  public static final c A;
  public static final c B;
  public static final c C;
  public static final c D;
  public static final c E;
  public static final c F;
  public static final c G;
  public static final c H;
  public static final c I;
  public static final c J;
  public static final c K;
  public static final c L;
  public static final c M;
  public static final c N;
  public static final c O;
  public static final c P;
  public static final c Q;
  public static final c R;
  public static final c S;
  public static final c T;
  public static final c U;
  public static final c V;
  public static final c W;
  public static final c X;
  public static final c Y;
  public static final c Z;
  public static final c a;
  public static final c aA;
  public static final c aB;
  public static final c aC;
  public static final c aD;
  public static final c aE;
  public static final c aF;
  public static final c aG;
  public static final c aH;
  public static final c aI;
  public static final c aJ;
  public static final c aK;
  public static final c aL;
  public static final c aM;
  public static final c aN;
  public static final c aO;
  public static final c aP;
  public static final c aQ;
  public static final c aR;
  public static final c aS;
  public static final c aT;
  public static final c aU;
  public static final c aV;
  public static final c aW;
  public static final c aX;
  public static final c aY;
  public static final c aZ;
  public static final c aa;
  public static final c ab;
  public static final c ac;
  public static final c ad;
  public static final c ae;
  public static final c af;
  public static final c ag;
  public static final c ah;
  public static final c ai;
  public static final c aj;
  public static final c ak;
  public static final c al;
  public static final c am;
  public static final c an;
  public static final c ao;
  public static final c ap;
  public static final c aq;
  public static final c ar;
  public static final c as;
  public static final c at;
  public static final c au;
  public static final c av;
  public static final c aw;
  public static final c ax;
  public static final c ay;
  public static final c az;
  public static final c b;
  public static final c bA;
  public static final c bB;
  public static final c bC;
  public static final c bD;
  public static final c bE;
  public static final c bF;
  public static final c bG;
  public static final c bH;
  public static final c bI;
  public static final c bJ;
  public static final c bK;
  public static final c bL;
  public static final c bM;
  public static final c bN;
  public static final c bO;
  public static final c bP;
  public static final c bQ;
  public static final c bR;
  public static final c bS;
  public static final c bT;
  public static final c bU;
  public static final c bV;
  public static final c bW;
  public static final c bX;
  public static final c bY;
  public static final c bZ;
  public static final c ba;
  public static final c bb;
  public static final c bc;
  public static final c bd;
  public static final c be;
  public static final c bf;
  public static final c bg;
  public static final c bh;
  public static final c bi;
  public static final c bj;
  public static final c bk;
  public static final c bl;
  public static final c bm;
  public static final c bn;
  public static final c bo;
  public static final c bp;
  public static final c bq;
  public static final c br;
  public static final c bs;
  public static final c bt;
  public static final c bu;
  public static final c bv;
  public static final c bw;
  public static final c bx;
  public static final c by;
  public static final c bz;
  public static final c c;
  public static final c ca;
  public static final c cb;
  public static final c cc;
  public static final c cd;
  public static final c ce;
  public static final c cf;
  public static final c cg;
  public static final c ch;
  public static final c ci;
  public static final c cj;
  public static final c ck;
  public static final c cl;
  public static final c cm;
  public static final c cn;
  public static final c co;
  public static final c cp;
  public static final c cq;
  public static final c cr;
  public static final c cs;
  public static final c ct;
  public static final c cu;
  public static final c cv;
  public static final c cw;
  public static final c cx;
  private static final c cy;
  private static byte[] cz;
  public static final c d;
  public static final c e;
  public static final c f;
  public static final c g;
  public static final c h;
  public static final c i;
  public static final c j;
  public static final c k;
  public static final c l;
  public static final c m;
  public static final c n;
  public static final c o;
  public static final c p;
  public static final c q;
  public static final c r;
  public static final c s;
  public static final c t;
  public static final c u;
  public static final c v;
  public static final c w;
  public static final c x;
  public static final c y;
  public static final c z;
  
  static
  {
    c.a(0, "gads:sdk_core_experiment_id");
    bE = c.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    c.a(0, "gads:sdk_core_js_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.js");
    Boolean localBoolean1 = Boolean.valueOf(false);
    c.a(0, "gads:request_builder:singleton_webview", localBoolean1);
    c.a(0, "gads:request_builder:singleton_webview_experiment_id");
    Boolean localBoolean2 = Boolean.valueOf(true);
    c.a(0, "gads:sdk_use_dynamic_module", localBoolean2);
    c.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    bG = c.a(0, "gads:sdk_crash_report_enabled", localBoolean1);
    ab = c.a(0, "gads:report_dynamite_crash_in_background_thread", localBoolean1);
    bH = c.a(0, "gads:sdk_crash_report_full_stacktrace", localBoolean1);
    bF = c.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    bO = c.a(1, "gads:trapped_exception_sample_rate", 0.01F);
    c.a(0, "gads:block_autoclicks_experiment_id");
    c.a(0, "gads:spam_app_context:experiment_id");
    c.a(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    cf = c.a(1, "gads:video_exo_player:version", "1");
    cb = c.a(1, "gads:video_exo_player:connect_timeout", 8000);
    ce = c.a(1, "gads:video_exo_player:read_timeout", 8000);
    cc = c.a(1, "gads:video_exo_player:loading_check_interval", 1048576);
    cd = c.a(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    bY = c.a(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    c.a(0, "gads:video_stream_cache:experiment_id");
    co = c.a(1, "gads:video_stream_cache:limit_count", 5);
    cp = c.a(1, "gads:video_stream_cache:limit_space", 8388608);
    ct = c.a(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    cq = c.a(1, "gads:video_stream_cache:limit_time_sec", 300L);
    cr = c.a(1, "gads:video_stream_cache:notify_interval_millis", 125L);
    cs = c.a(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    ck = c.a(0, "gads:video:metric_reporting_enabled", localBoolean1);
    cj = c.a(1, "gads:video:metric_frame_hash_times", "");
    ci = c.a(1, "gads:video:metric_frame_hash_time_leniency", 500L);
    cg = c.a(1, "gads:video:force_watermark", localBoolean1);
    cu = c.a(1, "gads:video:surface_update_min_spacing_ms", 1000L);
    cl = c.a(1, "gads:video:spinner:enabled", localBoolean1);
    cn = c.a(1, "gads:video:spinner:scale", 4);
    cm = c.a(1, "gads:video:spinner:jank_threshold_ms", 50L);
    bX = c.a(1, "gads:video:aggressive_media_codec_release", localBoolean1);
    aT = c.a(1, "gads:memory_bundle:debug_info", localBoolean1);
    bZ = c.a(1, "gads:video:codec_query_mime_types", "");
    ca = c.a(1, "gads:video:codec_query_minimum_version", 16);
    c.a(0, "gads:ad_id_app_context:ping_ratio", 0.0F);
    c.a(0, "gads:ad_id_use_shared_preference:experiment_id");
    c.a(0, "gads:ad_id_use_shared_preference:enabled", localBoolean1);
    c.a(0, "gads:ad_id_use_shared_preference:ping_ratio", 0.0F);
    c.a(0, "gads:ad_id_use_persistent_service:enabled", localBoolean1);
    c.a(0, "gads:ad_id:use_ipc:enabled", localBoolean1);
    aV = c.a(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    aW = c.a(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    aX = c.a(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    aY = c.a(1, "gad:mraid:version", "2.0");
    aU = c.a(1, "gads:mraid:unload", localBoolean1);
    M = c.a(0, "gads:enabled_sdk_csi", localBoolean1);
    N = c.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    cx = c.a(0, "gads:sdk_csi_write_to_file", localBoolean1);
    c.a(0, "gads:enable_content_fetching", localBoolean2);
    c.a(0, "gads:content_length_weight", 1);
    c.a(0, "gads:content_age_weight", 1);
    c.a(0, "gads:min_content_len", 11);
    c.a(0, "gads:fingerprint_number", 10);
    c.a(0, "gads:sleep_sec", 10);
    c.a(1, "gads:content_vertical_fingerprint_number", 100);
    c.a(1, "gads:content_vertical_fingerprint_bits", 23);
    c.a(1, "gads:content_vertical_fingerprint_ngram", 3);
    c.a(1, "gads:content_fetch_view_tag_id", "googlebot");
    c.a(1, "gads:content_fetch_exclude_view_tag", "none");
    c.a(1, "gads:content_fetch_disable_get_title_from_webview", localBoolean1);
    c.a(0, "gads:app_index:without_content_info_present:enabled", localBoolean2);
    c.a(0, "gads:app_index:timeout_ms", 1000L);
    c.a(0, "gads:app_index:experiment_id");
    f = c.a(0, "gads:ad_key_enabled", localBoolean1);
    c.a(1, "gads:sai:enabled", localBoolean2);
    c.a(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    c.a(1, "gads:sai:impression_ping_schema_v2", "^[^?]*/adview.*");
    c.a(1, "gads:sai:using_macro:enabled", localBoolean1);
    c.a(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    bB = c.a(1, "gads:sai:timeout_ms", -1L);
    c.a(1, "gads:sai:scion_thread_pool_size", 5);
    c.a(1, "gads:sai:app_measurement_enabled", localBoolean1);
    c.a(1, "gads:sai:force_through_reflection", localBoolean2);
    c.a(1, "gads:sai:gmscore_availability_check_disabled", localBoolean1);
    bC = c.a(1, "gads:sai:logging_disabled_for_drx", localBoolean1);
    p = c.a(1, "gads:interstitial:app_must_be_foreground:enabled", localBoolean1);
    c.a(0, "gads:webview_cache_version", 0);
    bR = c.a(0, "gads:corewebview:adwebview_factory:enable", localBoolean1);
    bS = c.a(0, "gads:corewebview:javascript_engine", localBoolean1);
    aH = c.a(1, "gad:webview:inject_scripts", localBoolean1);
    c.a(0, "gads:webview:permission:disabled", localBoolean1);
    c.b(0, "gads:pan:experiment_id");
    c.a(1, "gads:new_rewarded_ad:enabled", localBoolean2);
    bw = c.a(1, "gads:rewarded:adapter_initialization_enabled", localBoolean1);
    bx = c.a(1, "gads:rewarded:adapter_timeout_ms", 20000L);
    by = c.a(1, "gads:rewarded:ad_metadata_enabled", localBoolean1);
    bv = c.a(1, "gads:rewarded:ssv_custom_data_enabled", localBoolean2);
    bf = c.a(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    r = c.a(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5L));
    e = c.a(1, "gads:adid_values_in_adrequest:enabled", localBoolean1);
    d = c.a(1, "gads:adid_values_in_adrequest:timeout", 2000L);
    Y = c.a(1, "gads:disable_adid_values_in_ms", localBoolean1);
    c.a(0, "gads:ad_serving:enabled", localBoolean2);
    bj = c.a(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    bV = c.a(1, "gads:custom_close_blocking:enabled", localBoolean1);
    bW = c.a(1, "gads:disabling_closable_area:enabled", localBoolean1);
    c.a(1, "gads:impression_optimization_enabled", localBoolean1);
    c.a(1, "gads:banner_ad_pool:schema", "customTargeting");
    c.a(1, "gads:banner_ad_pool:max_queues", 3);
    c.a(1, "gads:banner_ad_pool:max_pools", 3);
    aL = c.a(1, "gads:interstitial_ad_pool:enabled", localBoolean1);
    aM = c.a(1, "gads:interstitial_ad_pool:enabled_for_rewarded", localBoolean1);
    c.a(1, "gads:interstitial_ad_pool:schema", "customTargeting");
    c.a(1, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    c.a(1, "gads:interstitial_ad_pool:max_pools", 3);
    c.a(1, "gads:interstitial_ad_pool:max_pool_depth", 2);
    c.a(1, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    c.a(1, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    c.a(1, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    c.a(1, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    c.a(1, "gads:interstitial_ad_pool:discard_thresholds", 0L);
    c.a(1, "gads:interstitial_ad_pool:miss_thresholds", 0L);
    c.a(1, "gads:interstitial_ad_pool:discard_asymptote", 0.0F);
    c.a(1, "gads:interstitial_ad_pool:miss_asymptote", 0.0F);
    ag = c.a(0, "gads:debug_logging_feature:enable", localBoolean1);
    ak = c.a(0, "gads:debug_logging_feature:intercept_web_view", localBoolean1);
    cy = c.a(1, "gads:heap_wastage:bytes", 0);
    bM = c.a(1, "gads:spherical_video:vertex_shader", "");
    bL = c.a(1, "gads:spherical_video:fragment_shader", "");
    at = c.a(0, "gads:log:verbose_enabled", localBoolean1);
    aG = c.a(1, "gads:include_local_global_rectangles", localBoolean1);
    cv = c.a(1, "gads:position_watcher:throttle_ms", 200L);
    X = c.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    aB = c.a(1, "gads:gen204_signals:enabled", localBoolean1);
    cw = c.a(0, "gads:webview:error_reporting_enabled", localBoolean1);
    c.a(0, "gads:adid_reporting:enabled", localBoolean1);
    c.a(0, "gads:ad_settings_page_reporting:enabled", localBoolean1);
    c.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", localBoolean1);
    c.a(1, "gads:rtb_signal_timeout_ms", 1000L);
    bz = c.a(1, "gads:rtb_cld:enabled", localBoolean1);
    bs = c.a(0, "gads:resolve_future:default_timeout_ms", 30000L);
    g = c.a(0, "gads:ad_loader:timeout_ms", 60000L);
    bq = c.a(0, "gads:rendering:timeout_ms", 60000L);
    l = c.a(0, "gads:adshield:enable_adshield_instrumentation", localBoolean1);
    bK = c.a(1, "gads:gestures:task_timeout", 2000L);
    b = c.a(1, "gads:gestures:asig:enabled", localBoolean1);
    a = c.a(1, "gads:gestures:ans:enabled", localBoolean1);
    bN = c.a(1, "gads:gestures:tos:enabled", localBoolean1);
    t = c.a(1, "gads:gestures:brt:enabled", localBoolean1);
    q = c.a(1, "gads:signal:app_permissions:disabled", localBoolean1);
    aJ = c.a(1, "gads:gestures:inthex:enabled", localBoolean1);
    aj = c.a(1, "gads:gestures:hpk:enabled", localBoolean2);
    m = c.a(1, "gads:gestures:pk", "");
    bQ = c.a(1, "gads:gestures:bs:enabled", localBoolean2);
    o = c.a(1, "gads:gestures:check_initialization_thread:enabled", localBoolean1);
    n = c.a(1, "gads:gestures:get_query_in_non_ui_thread:enabled", localBoolean2);
    aA = c.a(0, "gass:enabled", localBoolean2);
    az = c.a(0, "gass:enable_int_signal", localBoolean2);
    ay = c.a(0, "gass:enable_ad_attestation_signal", localBoolean2);
    c.a(0, "gads:adid_notification:first_party_check:enabled", localBoolean2);
    c.a(1, "gads:sdk_core_constants:experiment_id");
    bD = c.a(1, "gads:sdk_core_constants:caps", "");
    aR = c.a(0, "gads:js_flags:update_interval", TimeUnit.HOURS.toMillis(12L));
    aQ = c.a(0, "gads:js_flags:mf", localBoolean1);
    c.a(1, "gads:js_flags:disable_phenotype", localBoolean1);
    P = c.a(0, "gads:custom_render:ping_on_ad_rendered", localBoolean1);
    aZ = c.a(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    c.a(0, "gads:native:engine_js_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/native_ads.js");
    c.a(1, "gads:native:video_url", "//imasdk.googleapis.com/admob/sdkloader/native_video.html");
    ba = c.a(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    ch = c.a(1, "gads:native_video_load_timeout", 10);
    bh = c.a(1, "gads:omid:native_webview_load_timeout", 2000);
    c = c.a(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    as = c.a(1, "gads:enable_store_active_view_state", localBoolean1);
    ar = c.a(1, "gads:enable_singleton_broadcast_receiver", localBoolean1);
    am = c.a(1, "gads:native:media_view_match_parent:enabled", localBoolean1);
    F = c.a(1, "gads:native:count_impression_for_assets", localBoolean1);
    O = c.a(1, "gads:native:custom_one_point_five_click:enable", localBoolean2);
    bP = c.a(1, "gads:unified_native_ad:enable", localBoolean2);
    aI = c.a(1, "gads:instream_ad:enabled", localBoolean2);
    bU = c.a(1, "gads:fluid_ad:use_wrap_content_height", localBoolean1);
    c.a(1, "gads:auto_location_for_coarse_permission", localBoolean1);
    c.b(1, "gads:auto_location_for_coarse_permission:experiment_id");
    s = c.a(1, "gads:auto_location_timeout", 2000L);
    c.b(1, "gads:auto_location_timeout:experiment_id");
    c.a(1, "gads:auto_location_interval", -1L);
    c.b(1, "gads:auto_location_interval:experiment_id");
    c.a(0, "gads:auto_location_interval:without_thread", localBoolean2);
    av = c.a(1, "gads:fetch_app_settings_using_cld:enabled", localBoolean1);
    c.a(1, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    c.a(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    c.a(0, "gads:afs:csa:experiment_id");
    I = c.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    K = c.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    J = c.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    L = c.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    H = c.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    G = c.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    bk = c.a(1, "gads:parental_controls:timeout", 2000L);
    c.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    c.a(0, "gads:safe_browsing:safety_net:delay_ms", 2000L);
    bA = c.a(0, "gads:safe_browsing:debug", localBoolean1);
    c.a(1, "gads:cache:ad_request_timeout_millis", 250);
    c.a(1, "gads:cache:max_concurrent_downloads", 10);
    c.a(1, "gads:cache:javascript_timeout_millis", 5000L);
    u = c.a(1, "gads:cache:bind_on_foreground", localBoolean1);
    v = c.a(1, "gads:cache:bind_on_init", localBoolean1);
    w = c.a(1, "gads:cache:bind_on_request", localBoolean1);
    x = c.a(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30L));
    A = c.a(1, "gads:cache:use_cache_data_source", localBoolean1);
    B = c.a(1, "gads:cache:connection_per_read", localBoolean1);
    z = c.a(1, "gads:cache:connection_timeout", 5000L);
    y = c.a(1, "gads:cache:read_only_connection_timeout", 5000L);
    bT = c.a(1, "gads:http_assets_cache:enabled", localBoolean1);
    aC = c.a(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    aD = c.a(1, "gads:http_assets_cache:time_out", 100);
    af = c.a(1, "gads:chrome_custom_tabs_browser:enabled", localBoolean1);
    Z = c.a(1, "gads:chrome_custom_tabs:disabled", localBoolean1);
    S = c.a(1, "gads:debug_hold_gesture:enabled", localBoolean1);
    T = c.a(1, "gads:debug_hold_gesture:time_millis", 2000L);
    R = c.a(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    aF = c.a(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    U = c.a(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    Q = c.a(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    V = c.a(1, "gads:drx_debug:timeout_ms", 5000);
    bl = c.a(1, "gad:pixel_dp_comparision_multiplier", 1);
    aK = c.a(1, "gad:interstitial_for_multi_window", localBoolean1);
    aN = c.a(1, "gad:interstitial_ad_stay_active_in_multi_window", localBoolean1);
    aO = c.a(1, "gad:interstitial_multi_window_method", localBoolean1);
    E = c.a(1, "gad:interstitial:close_button_padding_dip", 0);
    C = c.a(1, "gads:clearcut_logging:enabled", localBoolean1);
    D = c.a(1, "gads:clearcut_logging:write_to_file", localBoolean1);
    ax = c.a(0, "gad:force_local_ad_request_service:enabled", localBoolean1);
    bn = c.a(1, "gad:publisher_testing:force_local_request:enabled", localBoolean1);
    bp = c.a(1, "gad:publisher_testing:force_local_request:enabled_list", "");
    bo = c.a(1, "gad:publisher_testing:force_local_request:disabled_list", "");
    aw = c.a(0, "gad:force_dynamite_loading_enabled", localBoolean1);
    c.a(0, "gad:dynamite_module:experiment_id");
    aE = c.a(1, "gad:http_redirect_max_count:times", 8);
    bg = c.a(1, "gads:omid:enabled", localBoolean1);
    W = c.a(1, "gads:omid:destroy_webview_delay", 1000);
    c.a(0, "gads:nonagon:red_button", localBoolean1);
    c.a(1, "gads:nonagon:banner:enabled", localBoolean1);
    c.a(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    c.a(1, "gads:nonagon:interstitial:enabled", localBoolean1);
    c.a(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    c.a(1, "gads:nonagon:rewardedvideo:enabled", localBoolean1);
    c.a(1, "gads:nonagon:mobile_ads_setting_manager:enabled", localBoolean1);
    be = c.a(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    c.a(1, "gads:nonagon:nativead:enabled", localBoolean1);
    c.a(1, "gads:nonagon:nativead:app_name", "(?!)");
    bb = c.a(1, "gads:nonagon:banner:check_dp_size", localBoolean1);
    bd = c.a(1, "gads:nonagon:rewarded:load_multiple_ads", localBoolean2);
    bt = c.a(1, "gads:nonagon:return_last_error_code", localBoolean1);
    bu = c.a(1, "gads:nonagon:return_no_fill_error_code", localBoolean1);
    bc = c.a(1, "gads:nonagon:continue_on_no_fill", localBoolean1);
    bi = c.a(1, "gads:nonagon:open_not_loaded_interstitial", localBoolean2);
    bJ = c.a(1, "gads:nonagon:separate_timeout:enabled", localBoolean1);
    br = c.a(1, "gads:nonagon:request_timeout:seconds", 60);
    aS = c.a(0, "gads:nonagon:limit_ad_request_connection", localBoolean2);
    aP = c.a(1, "gads:nonagon:javascript_ad_request:enabled", localBoolean1);
    c.a(1, "gads:nonagon:service:enabled", localBoolean1);
    ac = c.a(1, "gads:signals:ad_id_info:enabled", localBoolean1);
    ad = c.a(1, "gads:signals:app_index:enabled", localBoolean1);
    ae = c.a(1, "gads:signals:cache:enabled", localBoolean1);
    ah = c.a(1, "gads:signals:doritos:enabled", localBoolean1);
    ai = c.a(1, "gads:signals:doritos:v1:enabled", localBoolean1);
    al = c.a(1, "gads:signals:location:enabled", localBoolean1);
    c.a(1, "gads:signals:network_prediction:enabled", localBoolean1);
    an = c.a(1, "gads:signals:parental_control:enabled", localBoolean1);
    au = c.a(1, "gads:signals:video_decoder:enabled", localBoolean1);
    bI = c.a(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000L);
    bm = c.a(0, "gads:public_beta:traffic_multiplier", "1.0");
    j = c.a(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    k = c.a(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 27);
    h = c.a(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 26);
    i = c.a(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 27);
    aq = c.a(0, "gads:rewarded_sku:enabled", localBoolean2);
    c.a(0, "gads:rewarded_sku:override_test:enabled", localBoolean1);
    ao = c.a(1, "gads:consent:shared_preference_reading:enabled", localBoolean2);
    ap = c.a(1, "gads:consent:iab_consent_info:enabled", localBoolean2);
    c.a(1, "gads:nativeads:image:sample:enabled", localBoolean2);
    c.a(1, "gads:nativeads:image:sample:pixels", 1048576);
    aa = c.a(0, "gads:dynamite_load:fail:sample_rate", 10000);
    c.a(0, "gads:service:webview:enable_directory_suffix", localBoolean2);
  }
  
  public static List a()
  {
    return u.h.c.a();
  }
  
  public static void a(Context paramContext)
  {
    bo.a(paramContext, new o(paramContext));
    int i1 = ((Integer)cy.a()).intValue();
    if ((i1 > 0) && (cz == null)) {
      cz = new byte[i1];
    }
  }
  
  public static void a(Context paramContext, JSONObject paramJSONObject)
  {
    Object localObject = u.h.d;
    paramContext = paramContext.getSharedPreferences("google_ads_flags", 0).edit();
    localObject = u.h.c.b.iterator();
    while (((Iterator)localObject).hasNext())
    {
      c localc = (c)((Iterator)localObject).next();
      if (localc.c == 1) {
        localc.a(paramContext, localc.a(paramJSONObject));
      }
    }
    if (paramJSONObject != null) {
      paramContext.putString("flag_configuration", paramJSONObject.toString());
    }
    for (;;)
    {
      paramJSONObject = u.h.d;
      paramContext.commit();
      return;
      k.c("Flag Json is null.");
    }
  }
  
  public static List b()
  {
    Object localObject = u.h.c;
    List localList = ((i)localObject).a();
    localObject = ((i)localObject).c.iterator();
    while (((Iterator)localObject).hasNext())
    {
      String str = (String)((c)((Iterator)localObject).next()).a();
      if (str != null) {
        localList.add(str);
      }
    }
    return localList;
  }
}


/* Location:              /home/chengjian/CM_test/gp/apk/a.jar!/com/google/android/gms/ads/internal/f/n.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */