package com.tencent.mm.storage;

import android.content.Context;
import android.util.SparseArray;
import com.tencent.gmtrace.GMTrace;
import com.tencent.mm.compatible.util.e;
import com.tencent.mm.sdk.a.b;
import com.tencent.mm.sdk.platformtools.aa;
import com.tencent.mm.sdk.platformtools.bf;
import com.tencent.mm.sdk.platformtools.v;
import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import junit.framework.Assert;

public final class w
{
  public static String hgg;
  public static final String uxu;
  
  static
  {
    GMTrace.i(13536663175168L, 100856);
    hgg = e.hgg;
    uxu = aa.getContext().getFilesDir() + "/xlog";
    if (b.bIk()) {
      Assert.assertTrue(bKR());
    }
    GMTrace.o(13536663175168L, 100856);
  }
  
  private w()
  {
    GMTrace.i(13536126304256L, 100852);
    GMTrace.o(13536126304256L, 100852);
  }
  
  private static final String QK(String paramString)
  {
    GMTrace.i(13536528957440L, 100855);
    String[] arrayOfString = paramString.split("_");
    if ((arrayOfString == null) || (arrayOfString.length < 4))
    {
      if (arrayOfString == null) {}
      for (i = -1;; i = arrayOfString.length)
      {
        v.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: key:%s split by '_'  fileds len too short : %d , at least 4", new Object[] { paramString, Integer.valueOf(i) });
        GMTrace.o(13536528957440L, 100855);
        return null;
      }
    }
    int i = 0;
    while (i < arrayOfString.length)
    {
      if ((arrayOfString[i] == null) || (arrayOfString[i].length() <= 0))
      {
        v.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name:%s , [%s] too short ( <1 ) ", new Object[] { paramString, arrayOfString[i] });
        GMTrace.o(13536528957440L, 100855);
        return null;
      }
      i += 1;
    }
    i = arrayOfString.length - 1;
    String str = arrayOfString[i];
    if (str.equals("SYNC"))
    {
      i -= 1;
      str = arrayOfString[i];
    }
    for (;;)
    {
      if (i < 3)
      {
        if (arrayOfString == null) {
          i = -1;
        }
        v.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name:%s split by '_'  fileds len too short : %d , at least 3", new Object[] { paramString, Integer.valueOf(i) });
      }
      if ((!str.equals("INT")) && (!str.equals("LONG")) && (!str.equals("STRING")) && (!str.equals("BOOLEAN")) && (!str.equals("FLOAT")) && (!str.equals("DOUBLE")))
      {
        v.e("MicroMsg.ConstantsStorage", "BusinessInfoKey parse failed: name[%s], invalid type:%s ", new Object[] { paramString, str });
        GMTrace.o(13536528957440L, 100855);
        return null;
      }
      paramString = paramString.substring(0, paramString.lastIndexOf(str) - 1);
      GMTrace.o(13536528957440L, 100855);
      return paramString;
    }
  }
  
  private static final boolean bKR()
  {
    GMTrace.i(13536260521984L, 100853);
    Field[] arrayOfField = w.class.getDeclaredFields();
    SparseArray localSparseArray = new SparseArray();
    int i = 0;
    while (i < arrayOfField.length)
    {
      Field localField = arrayOfField[i];
      if ((Modifier.isStatic(localField.getModifiers())) && ((localField.getName().startsWith("USERINFO_")) || (localField.getName().startsWith("NEW_BANDAGE_")) || (localField.getName().startsWith("DYNAMIC_CONFIG_"))) && (localField.getType().toString().equals("int"))) {}
      try
      {
        int j = localField.getInt(null);
        if (localSparseArray.get(j, null) != null)
        {
          v.e("MicroMsg.ConstantsStorage", "%s and %s has same value(0x%05X)!!!", new Object[] { localSparseArray.get(j), localField.getName(), Integer.valueOf(j) });
          GMTrace.o(13536260521984L, 100853);
          return false;
        }
        localSparseArray.put(j, localField.getName());
      }
      catch (IllegalArgumentException localIllegalArgumentException)
      {
        for (;;)
        {
          v.e("MicroMsg.ConstantsStorage", "exception:%s", new Object[] { bf.g(localIllegalArgumentException) });
        }
      }
      catch (IllegalAccessException localIllegalAccessException)
      {
        for (;;)
        {
          v.e("MicroMsg.ConstantsStorage", "exception:%s", new Object[] { bf.g(localIllegalAccessException) });
        }
      }
      i += 1;
    }
    if (localSparseArray.size() > 510)
    {
      v.e("MicroMsg.ConstantsStorage", "constants values size(%d) is over the limit(%d)!!!", new Object[] { Integer.valueOf(localSparseArray.size()), Integer.valueOf(510) });
      GMTrace.o(13536260521984L, 100853);
      return false;
    }
    v.i("MicroMsg.ConstantsStorage", "checkDuplicateUserInfo values size: %d", new Object[] { Integer.valueOf(localSparseArray.size()) });
    boolean bool = bKS();
    GMTrace.o(13536260521984L, 100853);
    return bool;
  }
  
  private static final boolean bKS()
  {
    GMTrace.i(13536394739712L, 100854);
    ArrayList localArrayList = new ArrayList(a.values().length);
    a[] arrayOfa = a.values();
    int j = arrayOfa.length;
    int i = 0;
    while (i < j)
    {
      Object localObject = arrayOfa[i];
      if ((localObject == null) || (((a)localObject).name() == null))
      {
        v.e("MicroMsg.ConstantsStorage", "BusinessInfoKey check error: info is null!!!");
        GMTrace.o(13536394739712L, 100854);
        return false;
      }
      localObject = QK(((a)localObject).name());
      if (bf.mA((String)localObject))
      {
        GMTrace.o(13536394739712L, 100854);
        return false;
      }
      if (localArrayList.contains(localObject))
      {
        v.e("MicroMsg.ConstantsStorage", "BusinessInfoKey check error: redefinition of [%s] which already defined!", new Object[] { localObject });
        GMTrace.o(13536394739712L, 100854);
        return false;
      }
      localArrayList.add(localObject);
      i += 1;
    }
    GMTrace.o(13536394739712L, 100854);
    return true;
  }
  
  public static enum a
  {
    static
    {
      GMTrace.i(13535992086528L, 100851);
      uxv = new a("USERINFO_REPORT_LAST_TIME_REPORT_DYNACFG_VER_LONG", 0);
      uxw = new a("USERINFO_REPORT_LAST_TIME_REPORT_VIDEO_SEND_RECV_COUNT_LONG", 1);
      uxx = new a("USERINFO_UPDATE_UPDATE_FLAG_LONG", 2);
      uxy = new a("USERINFO_UPDATE_UPDATE_VERION_LONG", 3);
      uxz = new a("USERINFO_UPDATE_UPDATE_TIME_LONG", 4);
      uxA = new a("USERINFO_WALLET_OFFLINE_IEMI_STRING_SYNC", 5);
      uxB = new a("USERINFO_WALLET_OFFLINE_CODE_VER_STRING", 6);
      uxC = new a("USERINFO_SHAKE_CARD_ENTRANCE_OPEN_BOOLEAN_SYNC", 7);
      uxD = new a("USERINFO_SHAKE_CARD_ENTRANCE_BEGIN_TIME_INT_SYNC", 8);
      uxE = new a("USERINFO_SHAKE_CARD_ENTRANCE_END_TIME_INT_SYNC", 9);
      uxF = new a("USERINFO_SHAKE_CARD_ENTRANCE_NAME_STRING_SYNC", 10);
      uxG = new a("USERINFO_SHAKE_CARD_FLOW_CONTROL_LEVEL_MIN_INT_SYNC", 11);
      uxH = new a("USERINFO_SHAKE_CARD_FLOW_CONTROL_LEVEL_MAX_INT_SYNC", 12);
      uxI = new a("USERINFO_SHAKE_CARD_ENTRANCE_TIP_STRING_SYNC", 13);
      uxJ = new a("USERINFO_SHAKE_CARD_ACTIVITY_TYPE_INT_SYNC", 14);
      uxK = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_ID_STRING_SYNC", 15);
      uxL = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_DESC_STRING_SYNC", 16);
      uxM = new a("USERINFO_SHAKE_CARD_ENTRANCE_RED_DOT_TEXT_STRING_SYNC", 17);
      uxN = new a("USERINFO_SHAKE_CARD_TAB_RED_DOT_ID_STRING_SYNC", 18);
      uxO = new a("USERINFO_SHAKE_CARD_TAB_RED_DOT_DESC_STRING_SYNC", 19);
      uxP = new a("USERINFO_GAME_SEARCH_LIST_UPDATE_TIME_LONG", 20);
      uxQ = new a("USERINFO_GAME_GLOBAL_CONFIG_UPDATE_TIME_LONG", 21);
      uxR = new a("USERINFO_EMOJI_BACKUP_OVERSIZE_BOOLEAN", 22);
      uxS = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_UPLODD_LONG", 23);
      uxT = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_DOWNLOAD_LONG", 24);
      uxU = new a("USERINFO_EMOJI_RECOVER_CUSTOM_EMOJI_BOOLEAN", 25);
      uxV = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_UPLODD_FINISH_BOOLEAN", 26);
      uxW = new a("USERINFO_EMOJI_STORE_LAST_REFRESH_TIME_LONG", 27);
      uxX = new a("USERINFO_EMOJI_STORE_RECOMMEND_LAST_UPDATE_TIME_LONG", 28);
      uxY = new a("USERINFO_EMOJI_STORE_NEW_ORIGINAL_BOOLEAN", 29);
      uxZ = new a("USERINFO_EMOJI_SYNC_CUSTOM_EMOJI_BATCH_DOWNLOAD_BOOLEAN", 30);
      uya = new a("USERINFO_EMOJI_SYNC_STORE_EMOJI_NEW_PANEL_BOOLEAN", 31);
      uyb = new a("USERINFO_EMOJI_STORE_NEW_DESIGNER_EMOJI_BOOLEAN", 32);
      uyc = new a("USERINFO_EMOJI_LAST_BATCH_EMOJI_DOWNLOAD_TIME_2_LONG", 33);
      uyd = new a("USERINFO_EMOJI_CLEAN_TEMP_FILE_TASK_LONG", 34);
      uye = new a("USERINFO_EMOJI_ENCODE_EMOJI_FILE_TASK_LONG", 35);
      uyf = new a("USERINFO_EMOJI_REPORT_CUSTOM_EMOJI_COUNT_LONG", 36);
      uyg = new a("USERINFO_EMOJI_REWARD_TIP_ENABLE_BOOLEAN", 37);
      uyh = new a("USERINFO_EMOJI_CUREENT_VERSION_INT", 38);
      uyi = new a("USERINFO_EMOJI_UPDATE_EMOJI_GROUP_COUNT_BOOLEAN", 39);
      uyj = new a("USERINFO_EMOJI_NEW_EMOJI_INT", 40);
      uyk = new a("USERINFO_EMOJI_NEW_PANEL_INT", 41);
      uyl = new a("USERINFO_EMOJI_NEW_SUGGEST_INT", 42);
      uym = new a("USERINFO_EMOJI_EGG_INT", 43);
      uyn = new a("USERINFO_EMOJI_NEW_PANEL_NAME_STRING", 44);
      uyo = new a("USERINFO_LUCKY_MONEY_NEWYEAR_SWITCH_INT_SYNC", 45);
      uyp = new a("USERINFO_LUCKY_MONEY_NEWYEAR_LOCAL_SWITCH_INT", 46);
      uyq = new a("USERINFO_VOICEPRINT_MORE_TAB_DOT_SHOW_BOOLEAN", 47);
      uyr = new a("USERFINO_VOICEPRINT_SETTING_DOT_SHOW_BOOLEAN", 48);
      uys = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_DOT_SHOW_BOOLEAN", 49);
      uyt = new a("USERINFO_VOICEPRINT_SETTING_ACCOUNT_INFO_NEW_SHOW_BOOLEAN", 50);
      uyu = new a("USERINFO_REPORTNETTYPE_SEQ_LONG", 51);
      uyv = new a("USERINFO_REPORTNETTYPE_LASTREPORT_LONG", 52);
      uyw = new a("USERINFO_SELFINFO_SMALLIMGURL_STRING", 53);
      uyx = new a("USERINFO_SELFINFO_GETPROFILE_TIME_LONG", 54);
      uyy = new a("USERINFO_WALLET_BALANCE_NOTICE_STRING", 55);
      uyz = new a("USERINFO_WALLET_FETCH_NOTICE_STRING", 56);
      uyA = new a("USERINFO_WALLET_SUPPORT_BANK_WORD_STRING", 57);
      uyB = new a("USERINFO_NEED_TO_UPDATE_CONVERSATION_TIME_DIVIDER_LONG", 58);
      uyC = new a("USERINFO_EXPOSE_GETEXPOSESCENE_TIME_LONG", 59);
      uyD = new a("USERINFO_WXPHONE_PB_COUNT_INT", 60);
      uyE = new a("USERINFO_MALL_INDEX_HAS_SHOWN_FTF_NOTICE_BOOLEAN", 61);
      uyF = new a("USERINFO_PHONE_RECHARGE_CLOSED_BANNER_STRING", 62);
      uyG = new a("USERINFO_QQMAIL_UNREAD_COUNT_INT", 63);
      uyH = new a("USERINFO_AUTOGETBIG_IMG_MAX_LONG", 64);
      uyI = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_LONG", 65);
      uyJ = new a("USERINFO_AUTOGETBIG_IMG_CURRENT_DATE_LONG", 66);
      uyK = new a("USERINFO_SHAKE_KV_STAT_BLUETOOTH_POWER_STATE_TIME_LONG", 67);
      uyL = new a("USERINFO_SHAKE_TV_LATITUDE_STRING", 68);
      uyM = new a("USERINFO_SHAKE_TV_LONGTITUDE_STRING", 69);
      uyN = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_REDDOT_WORDING_STRING_SYNC", 70);
      uyO = new a("NEW_BANDAGE_DATASOURCE_NEW_CARD_ICON_STRING_SYNC", 71);
      uyP = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_REDDOT_WORDING_STRING_SYNC", 72);
      uyQ = new a("NEW_BANDAGE_WATCHER_SETTING_CARD_ENTRY_ICON_STRING_SYNC", 73);
      uyR = new a("USERINFO_CARDLAYOUT_TESTDATA_STRING", 74);
      uyS = new a("USERINFO_CARD_LAYOUT_BUF_DATA_STRING_SYNC", 75);
      uyT = new a("USERINFO_CARD_REDOT_WORDING_STRING_SYNC", 76);
      uyU = new a("USERINFO_CARD_REDOT_END_TIME_INT_SYNC", 77);
      uyV = new a("USERINFO_CARD_REDOT_BUFF_STRING_SYNC", 78);
      uyW = new a("USERINFO_CARD_REDOT_ICON_URL_STRING_SYNC", 79);
      uyX = new a("USERINFO_CARD_MSG_TIPS_TITLE_STRING_SYNC", 80);
      uyY = new a("USERINFO_CARD_MSG_TIPS_ICON_URL_STRING_SYNC", 81);
      uyZ = new a("USERINFO_CARD_GET_LAYOUT_SCENE_INT_SYNC", 82);
      uza = new a("USERINFO_CARD_GET_LAYOUT_JSON_STRING_SYNC", 83);
      uzb = new a("USERINFO_CARD_SHARECARD_LAYOUT_JSON_STRING_SYNC", 84);
      uzc = new a("USERINFO_CARD_REQUENCE_LONG_SYNC", 85);
      uzd = new a("USERINFO_CARD_IS_SHARE_CARD_ENTRANCE_OPEN_INT_SYNC", 86);
      uze = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_TIP_INT_SYNC", 87);
      uzf = new a("USERINFO_CARD_IS_SHOW_SHARE_CARD_ENTRANCE_TIP_INT_SYNC", 88);
      uzg = new a("USERINFO_CARD_IS_SHOW_MEMBERSHIP_TIP_INT_SYNC", 89);
      uzh = new a("USERINFO_CARD_SHARE_LIST_CLEAR_TIME_INT_SYNC", 90);
      uzi = new a("USERINFO_CARD_SHOW_WARNING_CARD_IDS_STRING_SYNC", 91);
      uzj = new a("USERINFO_CARD_HAS_UPDATE_CARD_TYPE_INT_SYNC", 92);
      uzk = new a("USERINFO_CARD_MSG_CARD_ID_STRING_SYNC", 93);
      uzl = new a("USERINFO_CARD_MSG_NEED_CHECK_BOOLEAN_SYNC", 94);
      uzm = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_BOOLEAN_SYNC", 95);
      uzn = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_HWFPMANAGER_BOOLEAN_SYNC", 96);
      uzo = new a("USERINFO_WALLET_FINGERPRINT_SWITCH_IS_NOT_NEW_BOOLEAN_SYNC", 97);
      uzp = new a("USERINFO_FINGER_PRINT_IS_OPEN_BOOLEAN_SYNC", 98);
      uzq = new a("USERINFO_FINGER_PRINT_IS_SO_LOAD_SUCCESS_BOOLEAN_SYNC", 99);
      uzr = new a("USERINFO_FINGER_PRINT_IS_FORCE_PWD_MODE_BOOLEAN_SYNC", 100);
      uzs = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_BOOLEAN_SYNC", 101);
      uzt = new a("USERINFO_FINGER_PRINT_IS_SO_LOADLIBRARY_SUCCESS_BOOLEAN_SYNC", 102);
      uzu = new a("USERINFO_FINGER_PRINT_IS_FIRST_SHOWN_BOOLEAN_SYNC", 103);
      uzv = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_IN_TRANSPARENT_NEW_BOOLEAN_SYNC", 104);
      uzw = new a("USERINFO_FINGER_PRINT_SHOW_OPEN_GUIDE_COUNT_INT_SYNC", 105);
      uzx = new a("USERINFO_FINGER_PRINT_LAST_IS_SEVERE_ERROR_BOOLEAN_SYNC", 106);
      uzy = new a("USERINFO_ABTEST_SERVER_TIMESTAMP_INT", 107);
      uzz = new a("USERINFO_ABTEST_LAST_UPDATE_TIME_LONG", 108);
      uzA = new a("USERINFO_ABTEST_UPDATE_TIME_INTERVAL_INT", 109);
      uzB = new a("USERINFO_NFC_CPU_CARD_CONFIG_STRING", 110);
      uzC = new a("USERINFO_BIND_MOBILE_XML_TIP_BOOLEAN", 111);
      uzD = new a("USERINFO_BIND_MOBILE_XML_FORCE_BIND_BOOLEAN", 112);
      uzE = new a("USERINFO_BIND_MOBILE_XML_WORDING_STRING", 113);
      uzF = new a("USERINFO_BIZ_ATTR_SYNC_OPEN_FLAG_INT", 114);
      uzG = new a("USERINFO_NFC_OPEN_SWITCH_INT_SYNC", 115);
      uzH = new a("USERINFO_NFC_OPEN_DEFAULT_SWITCH_INT_SYNC", 116);
      uzI = new a("BUSINESS_SNS_ADLOG_FREQUENCY_INT", 117);
      uzJ = new a("BUSINESS_SNS_ADLOG_CNTTIME_INT", 118);
      uzK = new a("USERINFO_NFC_OPEN_SWITCH_WORDING_STRING_SYNC", 119);
      uzL = new a("USERINFO_IPCALL_COUNTRY_CODE_RESTRCTION_INT", 120);
      uzM = new a("USERINFO_IPCALL_COUNTRY_CODE_LASTUPDATE_TIME_LONG", 121);
      uzN = new a("USERINFO_IPCALL_FIRST_IN_BOOLEAN", 122);
      uzO = new a("USERINFO_IPCALL_ADDRESS_LASTREPORT_TIME_LONG", 123);
      uzP = new a("USERINFO_IPCALL_ADDRESS_GETMFRIEND_LASTUPDATE_TIME_LONG", 124);
      uzQ = new a("USERINFO_IPCALL_ADDRESS_GETLOCATION_LASTUPDATE_TIME_LONG", 125);
      uzR = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_BOOLEAN", 126);
      uzS = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_SHOW_REDDOT_TYPE_INT", 127);
      uzT = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_STRING", 128);
      uzU = new a("USERFINO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_STRING", 129);
      uzV = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_CLEAR_TYPE_INT", 130);
      uzW = new a("USERINFO_IPCALL_ADDRESS_ACCOUNT_ACTIVITY_TYPE_VERSION_INT", 131);
      uzX = new a("USERFINO_IPCALL_RECHARGE_STRING", 132);
      uzY = new a("USERINFO_IPCALL_RECHARGE_SHOW_REDDOT_BOOLEAN", 133);
      uzZ = new a("USERINFO_IPCALL_PACKAGE_PURCHASE_STRING", 134);
      uAa = new a("USERINFO_IPCALL_EXCHANGE_RECORD_SHOW_REDDOT_BOOLEAN", 135);
      uAb = new a("USERFINO_IPCALL_HAS_ENTRY_BOOLEAN", 136);
      uAc = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_INT", 137);
      uAd = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_WORDING_STRING", 138);
      uAe = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_NEWXML_BOOLEAN", 139);
      uAf = new a("USERFINO_IPCALL_HAS_ENTRY_FIND_REDDOT_TYPE_INT", 140);
      uAg = new a("USERINFO_IPCALL_MSG_CENTER_SHOW_REDDOT_BOOLEAN", 141);
      uAh = new a("USERFINO_IPCALL_MSG_CENTER_SHOW_REDDOT_TYPE_INT", 142);
      uAi = new a("USERFINO_IPCALL_REDDOT_RECHARGE_VERSION_INT", 143);
      uAj = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_LAST_TIME_LONG", 144);
      uAk = new a("USERFINO_IPCALL_SHOW_FROM_VOIP_TIME_COUNT_INT", 145);
      uAl = new a("USERFINO_FAV_HAS_DB_DATATOTALLENGTH_BOOLEAN", 146);
      uAm = new a("USERFINO_FAV_USED_CAPACITY_LONG", 147);
      uAn = new a("USERFINO_FAV_TOTAL_CAPACITY_LONG", 148);
      uAo = new a("USERFINO_FAV_IS_FULL_BOOLEAN", 149);
      uAp = new a("USERFINO_IPCALL_SHOW_FEEDBACK_LAST_TIME_LONG", 150);
      uAq = new a("USERFINO_IPCALL_SHOW_FEEDBACK_TIME_COUNT_INT", 151);
      uAr = new a("USERFINO_IPCALL_HAS_ACTIVITY_BOOLEAN", 152);
      uAs = new a("USERFINO_IPCALL_ACTIVITY_STRING", 153);
      uAt = new a("USERINFO_SUBMENU_SHOW_TIT_BOOLEAN", 154);
      uAu = new a("USERINFO_PROFILE_WEIDIANINFO_STRING", 155);
      uAv = new a("GAME_DISCOVERY_ENTRANCE_MSGID_LONG_SYNC", 156);
      uAw = new a("GAME_INDEX_BUBBLE_MSGID_LONG_SYNC", 157);
      uAx = new a("GAME_MSG_ENTRANCE_MSGID_LONG_SYNC", 158);
      uAy = new a("GAME_GIFT_ENTRANCE_MSGID_LONG_SYNC", 159);
      uAz = new a("GAME_INDEX_FLOATLAYER_MSGID_LONG_SYNC", 160);
      uAA = new a("USERINFO_WELCOMEMSG_CONTENT_STRING", 161);
      uAB = new a("USERINFO_WELCOMEMSG_EXT_LASTTIME_LONG", 162);
      uAC = new a("USERINFO_WELCOMEMSG_EXT_SHOWCOUNT_LONG", 163);
      uAD = new a("USERINFO_RES_DOWNLOADER_CHECK_RES_UPDATE_INTERVAL_LONG", 164);
      uAE = new a("USERINFO_RES_DOWNLOADER_CHECK_RESUME_INTERVAL_LONG", 165);
      uAF = new a("USERINFO_LOAN_ENTRANCE_RED_POINT_INT", 166);
      uAG = new a("USERINFO_WEBVIEW_CLEAR_HOST_COOKIES_INTERVAL_LONG", 167);
      uAH = new a("USERINFO_IBEACON_PUSH_SHOP_ID_LONG", 168);
      uAI = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_METHOD_INT", 169);
      uAJ = new a("USERINFO_IBEACON_PUSH_CHANNEL_OPEN_TIME_LONG", 170);
      uAK = new a("USERINFO_IBEACON_SHAKE_TAB_DISPLAY_INT", 171);
      uAL = new a("USERINFO_IBEACON_SHAKE_IS_RANGING_INTERFACE_BOOLEAN", 172);
      uAM = new a("USERINFO_IBEACON_PUSH_BEACONINFO_STRING", 173);
      uAN = new a("USERINFO_IBEACON_PUSH_LAST_BEACONINFO_STRING", 174);
      uAO = new a("USERINFO_IBEACON_PUSH_IS_OPEN_BOOLEAN", 175);
      uAP = new a("USERINFO_IBEACON_PUSH_OPEN_TIEMSTAMP_LONG", 176);
      uAQ = new a("USERINFO_IBEACON_PUSH_IS_IN_SHAKEUI_BOOLEAN", 177);
      uAR = new a("USERINFO_IBEACON_SHAKE_TAB_IS_BLUETOOTH_RESIDENT_BOOLEAN", 178);
      uAS = new a("USERINFO_IBEACON_SHAKE_TAB_IS_CITY_RESIDENT_BOOLEAN", 179);
      uAT = new a("USERINFO_IBEACON_SHAKE_TAB_IS_UIN_RESIDENT_INT", 180);
      uAU = new a("USERINFO_IBEACON_SHAKE_TAB_RESIDENT_GATED_LAUNCH_INT", 181);
      uAV = new a("USERINFO_PROFILE_WEIDIANINFO_ALERT_INT", 182);
      uAW = new a("USERINFO_LAST_LOCATION_STRING", 183);
      uAX = new a("USERINFO_LAST_F2F_INVITE_TIME_LONG", 184);
      uAY = new a("USERINFO_F2F_DELAY_TIME_LONG", 185);
      uAZ = new a("USERINFO_MALL_INDEX_TYPE_NAME_LIST_STRING_SYNC", 186);
      uBa = new a("USERINFO_MALL_THIRD_PARTY_DISCLAIMER_STRING", 187);
      uBb = new a("USERINFO_SHAKE_TV_ACCURACY_STRING", 188);
      uBc = new a("USERINFO_IPCALL_ACCOUNT_CACHE_STRING", 189);
      uBd = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_DOWNLOAD_BOOLEAN", 190);
      uBe = new a("USERINFO_SET_CAN_WEBVIEW_CACHE_PRE_PUSH_DOWNLOAD_BOOLEAN", 191);
      uBf = new a("USERINFO_WEBVIEW_CACHE_CLEANUP_INTERVAL_LONG", 192);
      uBg = new a("USERINFO_TRICK_SOTER_BOOLEAN", 193);
      uBh = new a("USERINFO_CLEANUI_QQMGRINFO_STRING", 194);
      uBi = new a("USERINFO_POSITION_AT_CHATRECORD_FIRST_IN_BOOLEAN", 195);
      uBj = new a("USERINFO_HAD_SHOW_WALLET_MULTI_WALLET_GUIDE_BOOLEAN", 196);
      uBk = new a("USERINFO_WALLET_BULLETIN_GET_TIME_LONG", 197);
      uBl = new a("USERINFO_WALLET_BULLETIN_UPDATE_INTERVAL_LONG", 198);
      uBm = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRL_STRING_SYNC", 199);
      uBn = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIP_STRING_SYNC", 200);
      uBo = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFINDMORE_STRING_SYNC", 201);
      uBp = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKCAMERA_STRING_SYNC", 202);
      uBq = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKFULLSCREEN_STRING_SYNC", 203);
      uBr = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYOPEN_BOOLEAN_SYNC", 204);
      uBs = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCTRLHASSHOW_BOOLEAN_SYNC", 205);
      uBt = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT_INT_SYNC", 206);
      uBu = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLLUCKYCOUNT2_INT_SYNC", 207);
      uBv = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKPOST_STRING_SYNC", 208);
      uBw = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_CTRLMARKGOLDCAMERATIP_STRING_SYNC", 209);
      uBx = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_TIPMARKCAMERATIP_STRING_SYNC", 210);
      uBy = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_LEVELCTRL_STRING_SYNC", 211);
      uBz = new a("USERINFO_NEWYEAR_2016_HONGBAO_SNS_FLOW_CONTROL_CACHEBUFFER_STRING", 212);
      uBA = new a("USERINFO_NEWYEAR_2016_ACCEPT_CARD_ITEM_BUFFER_STRING_SYNC", 213);
      uBB = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_OPEN_SNS_PAY_INT_SYNC", 214);
      uBC = new a("USERINFO_NEWYEAR_2016_HONGBAO_CAN_OPEN_SNS_PAY_INT_SYNC", 215);
      uBD = new a("USERINFO_NEWYEAR_2016_HONGBAO_IS_WHITE_USER_INT_SYNC", 216);
      uBE = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_TITLE_STRING_SYNC", 217);
      uBF = new a("USERINFO_NEWYEAR_2016_HONGBAO_OPEN_SNS_PAY_WORDING_STRING_SYNC", 218);
      uBG = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_TITLE_STRING_SYNC", 219);
      uBH = new a("USERINFO_NEWYEAR_2016_HONGBAO_SET_SNS_PAY_WORDING_STRING_SYNC", 220);
      uBI = new a("USERINFO_NEWYEAR_2016_HONGBAO_HAS_SHOW_SNS_PAY_GUIDE_DIALOG_BOOLEAN_SYNC", 221);
      uBJ = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PATH_STRING_SYNC", 222);
      uBK = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_ID_STRING_SYNC", 223);
      uBL = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_AES_KEY_STRING_SYNC", 224);
      uBM = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_LENGTH_INT_SYNC", 225);
      uBN = new a("USERINFO_NEWYEAR_HONGBAO_IMAGE_PRESTRAIN_FLAG_INT_SYNC", 226);
      uBO = new a("USERINFO_FINGERPRINT_RETRY_TIME_INT_SYNC", 227);
      uBP = new a("USERINFO_FINGERPRINT_LAST_FREEZE_TIME_LONG_SYNC", 228);
      uBQ = new a("USERINFO_OVER_SEA_DOWNLOAD_X5_HAS_NOTIFY_BOOLEAN_SYNC", 229);
      uBR = new a("USERINFO_WALLET_PAY_DEDUCT_IS_NEW_BOOLEAN_SYNC", 230);
      uBS = new a("USERINFO_WALLET_FETCH_CHARGE_TIP_DIALOG_BOOLEAN_SYNC", 231);
      uBT = new a("USERINFO_WALLET_PREF_INFO_CACHE_TIME_LONG_SYNC", 232);
      uBU = new a("USERINFO_WALLET_PREF_INFO_EXPIRES_INT_SYNC", 233);
      uBV = new a("USERINFO_WALLET_BANKCARD_DETAIL_URL_STRING_SYNC", 234);
      uBW = new a("USERINFO_WALLET_BANKCARD_DETAIL_URL_TIMESTAMP_LONG_SYNC", 235);
      uBX = new a("USERINFO_WALLET_REALNAME_SWITCH_WORDING_STRING_SYNC", 236);
      uBY = new a("USERINFO_WALLET_REALNAME_DISCLAIMER_QUERY_EXPIRED_TIME_LONG_SYNC", 237);
      uBZ = new a("USERINFO_WALLET_DISCLAIMER_NEED_AGERR_INT_SYNC", 238);
      uCa = new a("USERINFO_WALLET_REALNAME_URL_STRING_SYNC", 239);
      uCb = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_SHOW_TIME_LONG_SYNC", 240);
      uCc = new a("USERINFO_WALLET_LBS_REPORT_CONFIG_STRING_SYNC", 241);
      uCd = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_TITLE_STRING_SYNC", 242);
      uCe = new a("USERINFO_WALLET_LBS_REPORT_DIALOG_CONTENT_STRING_SYNC", 243);
      uCf = new a("USERINFO_WALLET_RELEAY_NAME_TIP_CONTENT_STRING_SYNC", 244);
      uCg = new a("USERINFO_WALLET_RELEAY_NAME_BALANCE_CONTENT_STRING_SYNC", 245);
      uCh = new a("USERINFO_WALLET_DEDUCT_SELECT_WORDING_STRING", 246);
      uCi = new a("USERINFO_WALLET_DEDUCT_CHANGE_WORDING_STRING", 247);
      uCj = new a("USERINFO_MINIQB_SUPPORT_FILE_TYPE_STRING_SYNC", 248);
      uCk = new a("USERINFO_FACE_DETECTION_ENROLLED_BOOLEAN_SYNC", 249);
      uCl = new a("USERINFO_WALLET_MALLINDEX_OSDATA_TYPE_STRING_SYNC", 250);
      uCm = new a("USERINFO_WALLET_REGION_TYPE_INT_SYNC", 251);
      uCn = new a("USERINFO_RECHARGE_SHOW_REMIND_BOOLEAN", 252);
      uCo = new a("USERINFO_APP_BRAND_PUBLIC_LIB_UPDATE_NEXT_TIME_SEC_LONG", 253);
      uCp = new a("USERINFO_APP_BRAND_PUBLIC_LIB_USERNAME_STRING", 254);
      uCq = new a("USERINFO_APP_BRAND_PUBLIC_LIB_APPID_STRING", 255);
      uCr = new a("USERINFO_APP_BRAND_PRUNE_PKG_NEXT_TIME_SEC_LONG", 256);
      uCs = new a("USERINFO_APP_BRAND_USAGE_RECORD_SYNC_NEXT_TIME_SEC_LONG", 257);
      uCt = new a("USERINFO_APP_BRAND_USAGE_RECORD_HAS_FAVORITE_BOOLEAN", 258);
      uCu = new a("USERINFO_APP_BRAND_USAGE_RECORD_HAS_HISTORY_BOOLEAN", 259);
      uCv = new a("USERINFO_APP_BRAND_SHOW_HISTORY_COUNT_BOOLEAN", 260);
      uCw = new a("USERINFO_APP_BRAND_HISTORY_HAS_MORE_BOOLEAN", 261);
      uCx = new a("USERINFO_APP_BRAND_HISTORY_LIST_PAGING_LAST_SERVER_MIN_UPDATE_TIME_LONG", 262);
      uCy = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_END_TIME_SECOND_LONG", 263);
      uCz = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_MSG_ID_STRING", 264);
      uCA = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_PUSH_TIME_LONG", 265);
      uCB = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_SHOWTYPE_INT", 266);
      uCC = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_NEW_XML_REASON_INT", 267);
      uCD = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_TIPS_STRING", 268);
      uCE = new a("USERINFO_APP_BRAND_ENTRANCE_RED_DOT_HAS_REPORTED_SEE_RED_DOT_BOOLEAN", 269);
      uCF = new a("USERINFO_APP_BRAND_ENTRANCE_SHOW_NEW_BOOLEAN", 270);
      uCG = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_MSG_ID_STRING", 271);
      uCH = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_END_TIME_SECOND_LONG", 272);
      uCI = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_LAST_TIME_SECOND_LONG", 273);
      uCJ = new a("USERINFO_APP_BRAND_ENTRANCE_LOCATION_REPORT_FREQUENCY_SECOND_LONG", 274);
      uCK = new a("USERINFO_APP_BRAND_ENTRANCE_SHOW_RED_DOT_ONCE_BOOLEAN", 275);
      uCL = new a("USERINFO_APP_BRAND_ENTRANCE_HAS_SEEN_NEARBY_SHOWCASE_BOOLEAN_SYNC", 276);
      uCM = new a("USERINFO_APP_BRAND_CHATTING_BANNER_INFO_STRING_SYNC", 277);
      uCN = new a("USERINFO_EXT_SPORT_PKGNAME_STRING", 278);
      uCO = new a("USERINFO_SENSE_WHERE_LOCATION_STRING", 279);
      uCP = new a("USERINFO_LAST_GET_SENSE_WHERE_LOCATION_LONG", 280);
      uCQ = new a("USERINFO_LAST_START_SENSE_WHERE_LONG", 281);
      uCR = new a("USERINFO_REPORT_SD_STATUS_TIME_LONG", 282);
      uCS = new a("USERINFO_ADDRESS_HAS_SHOW_DISCLAIMER_DIALOG_BOOLEAN_SYNC", 283);
      uCT = new a("USERINFO_INVOICE_HAS_SHOW_DISCLAIMER_DIALOG_BOOLEAN_SYNC", 284);
      uCU = new a("USERINFO_ONLINE_VIDEO_INT", 285);
      uCV = new a("USERINFO_ADDRESS_HAS_SHOW_WALLETOFFLINE_DIALOG_BOOLEAN_SYNC", 286);
      uCW = new a("USERINFO_SERVICE_NOTIFY_MESSAGE_NOTICE_BOOLEAN_SYNC", 287);
      uCX = new a("USERINFO_WXA_CUSTOM_SESSION_MESSAGE_NOTICE_BOOLEAN_SYNC", 288);
      uCY = new a("USERINFO_WALLETDIGITAL_CERT_CRT_STRING_SYNC", 289);
      uCZ = new a("USERINFO_WALLETDIGITAL_CERT_NO_STRING_SYNC", 290);
      uDa = new a("USERINFO_WALLETDIGITAL_CERT_SHOW_INT_SYNC", 291);
      uDb = new a("USERINFO_ADDRESS_HAS_SHOW_WALLETOFFLINE2_DIALOG_BOOLEAN_SYNC", 292);
      uDc = new a("USERINFO_AA_MAX_PAYER_NUM_INT", 293);
      uDd = new a("USERINFO_AA_MAX_RECEIVER_NUM_INT", 294);
      uDe = new a("USERINFO_AA_MAX_TOTAL_USER_NUM_INT", 295);
      uDf = new a("USERINFO_AA_MAX_TOTAL_AMOUNT_LONG", 296);
      uDg = new a("USERINFO_AA_MAX_PER_AMOUNT_LONG", 297);
      uDh = new a("USERINFO_APP_BRAND_FAILED_FORMID_STRING", 298);
      uDi = new a("USERINFO_LOCAL_SIGHT_RECODER_INT_SYNC", 299);
      uDj = new a("USERINFO_LOCAL_SIGHT_ENCODEINSEND_INT_SYNC", 300);
      uDk = new a("USERINFO_LOCAL_SIGHT_PREWVIEWSIZE_INT_SYNC", 301);
      uDl = new a("USERINFO_LOCAL_SIGHT_BITRATE_INT_SYNC", 302);
      uDm = new a("USERINFO_LOCAL_SIGHT_DEBUGINFO_INT_SYNC", 303);
      uDn = new a("USERINFO_LOCAL_SIGHT_SET_SHUTTER_SOUND_INT_SYNC", 304);
      uDo = new a("USERINFO_LOCAL_SIGHT_CROP_INT_SYNC", 305);
      uDp = new a("USERINFO_LOCAL_SIGHT_OPENOLDSIGHT_INT_SYNC", 306);
      uDq = new a("USERINFO_LOCAL_SIGHT_SETTING_PRESET_INT_SYNC", 307);
      uDr = new a("USERINFO_LOCAL_SIGHT_THREADCOUNT_INT_SYNC", 308);
      uDs = new a("USERINFO_LOCAL_SIGHT_REALSCALE_INT_SYNC", 309);
      uDt = new a("USERINFO_LOCAL_SIGHT_FOCUS_INT_SYNC", 310);
      uDu = new a("USERINFO_LOCAL_SIGHT_FFMMPEGCUT_INT_SYNC", 311);
      uDv = new a("USERINFO_LOCAL_SIGHT_COMPRESS_TO_SINGLE_CHANNEL_INT_SYNC", 312);
      uDw = new a("USERINFO_LOCAL_SIGHT_CLIP_PREVIEW_MEDIA_PLAYER_INT_SYNC", 313);
      uDx = new a("USERINFO_LOCAL_SIGHT_AUDIO_RECORDER_TYPE_INT_SYNC", 314);
      uDy = new a("USERINFO_MMSIGHT_MEDIACODEC_COLORFORMAT_INT", 315);
      uDz = new a("USERINFO_WECHAT_DB_REPORT_LAST_TIME_LONG", 316);
      uDA = new a("USERINFO_WECHAT_FILE_SCAN_LAST_TIME_LONG", 317);
      uDB = new a("USERINFO_WECHAT_FILE_SCAN_INTERVAL_LONG", 318);
      uDC = new a("USERINFO_WECHAT_FILE_SCAN_WAIT_TIME_LONG", 319);
      uDD = new a("USERINFO_INSTALL_FIRST_TIME_LONG", 320);
      uDE = new a("USERINFO_INSTALL_FIRST_CLIENT_VERSION_INT", 321);
      uDF = new a("USERINFO_INSTALL_LAST_REPORT_TIME_LONG", 322);
      uDG = new a("USERINFO_MSG_SYNCHRONIZE_BOOLEAN", 323);
      uDH = new a("USERINFO_LOGIN_EXT_DEVICE_INFO_INT", 324);
      uDI = new a("USERINFO_BACKUP_PC_BACKUPING_BOOLEAN", 325);
      uDJ = new a("USERINFO_BACKUP_PC_RECOVERING_BOOLEAN", 326);
      uDK = new a("USERINFO_BACKUP_PC_MERGERING_BOOLEAN", 327);
      uDL = new a("USERINFO_BACKUP_MOVE_BACKUPING_BOOLEAN", 328);
      uDM = new a("USERINFO_BACKUP_MOVE_RECOVERING_BOOLEAN", 329);
      uDN = new a("USERINFO_BACKUP_MOVE_MERGERING_BOOLEAN", 330);
      uDO = new a("USERINFO_BACKUP_OLD_RECORDS_BOOLEAN", 331);
      uDP = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_LAST_TIME_LONG", 332);
      uDQ = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_INTERVAL_LONG", 333);
      uDR = new a("USERINFO_WECHAT_BACKUP_CHAT_SIZE_CALCULATE_WAIT_TIME_LONG", 334);
      uDS = new a("USERINFO_DELAY_TRANSFER_CONFIRM_WORDING_STRING", 335);
      uDT = new a("USERINFO_DELAY_TRANSFER_SWITCH_WORDING_STRING", 336);
      uDU = new a("USERINFO_DELAY_TRANSFER_REMIND_WORDING_STRING", 337);
      uDV = new a("USERINFO_DELAY_TRANSFER_EXPIRE_TIME_LONG", 338);
      uDW = new a("USERINFO_DELAY_TRANSFER_DESC_URL_STRING", 339);
      uDX = new a("USERINFO_DELAY_TRANSFER_DESC_URL_FLAG_INT", 340);
      uDY = new a("USERINFO_DELAY_TRANSFER_SHOW_SWITCH_FLAG_INT", 341);
      uDZ = new a("USERINFO_WEIXIN_CAMERA_STATE_INT", 342);
      uEa = new a("USERINFO_WEIXIN_CAMERASAVEIMAGE_STATE_BOOLEAN", 343);
      uEb = new a("USERINFO_WEIXIN_CAMERASAVEVIDEO_STATE_BOOLEAN", 344);
      uEc = new a("USERINFO_WALLET_REMITTANCE_STRING_SYNC", 345);
      uEd = new a("USERINFO_WALLET_HONGBAO_STRING_SYNC", 346);
      uEe = new a("USERINFO_WEBVIEW_KEEP_STRING_SYNC", 347);
      uEf = new a("USERINFO_WEBVIEW_KEEP_LAST_PAGE_STRING_SYNC", 348);
      uEg = new a("USERINFO_WEBVIEW_KEEP_LAST_PAGE_TITLE_STRING_SYNC", 349);
      uEh = new a("USERINFO_F2F_RING_TONE_STRING", 350);
      uEi = new a("USERINFO_WXA_SEARCH_INPUT_HINT_LANG_STRING_SYNC", 351);
      uEj = new a("USERINFO_WXA_SEARCH_INPUT_HINT_CONTENT_STRING_SYNC", 352);
      uEk = new a("USERINFO_WXA_SEARCH_INPUT_HINT_CONTENT_ID_STRING_SYNC", 353);
      uEl = new a("USERINFO_WXA_SEARCH_INPUT_HINT_UPDATE_TIME_LONG_SYNC", 354);
      uEm = new a("USERINFO_SHAKE_NEWYEAR_COOKIE_STRING", 355);
      uEn = new a("USERINFO_SNS_RECENT_LIMITED_ID_LONG_SYNC", 356);
      uEo = new a("USERINFO_VIDEO_NEED_RESET_EXTRACTOR_BOOLEAN", 357);
      uEp = new a("USERINFO_MALL_NEWS_MARKED_STRING_SYNC", 358);
      uEq = new a("USERINFO_LAUNCH_APP_NOT_ASK_PKG_STRING", 359);
      uEr = new a("USERINFO_WEBVIEW_KEEP_TOP_SCENE_INT_SYNC", 360);
      uEs = new a("USERINFO_SNS_INTRODUCE_SETTING_DISPLAY_BOOLEAN_SYNC", 361);
      uEt = new a("USERINFO_FACE_SHOW_TUTORIAL_BOOLEAN_SYNC", 362);
      uEu = new a("USERINFO_GAME_WEBVIEW_KEEP_LAST_PAGE_URL_STRING_SYNC", 363);
      uEv = new a("USERINFO_GAME_WEBVIEW_KEEP_LAST_PAGE_USERNAME_STRING_SYNC", 364);
      uEw = new a("USERINFO_GAME_WEBVIEW_KEEP_LAST_PAGE_TITLE_STRING_SYNC", 365);
      uEx = new a("USERINFO_HEAVY_USER_FLAG_LONG", 366);
      uEy = new a("USERINFO_HEAVY_USER_REPORT_TIME_LONG", 367);
      uEz = new a("USERINFO_HEAVY_USER_REPORT_TYPE_SD_FILE_SIZE_LONG", 368);
      uEA = new a("USERINFO_HEAVY_USER_REPORT_TYPE_SD_FILE_RATIO_LONG", 369);
      uEB = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_SIZE_LONG", 370);
      uEC = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_MESSAGE_LONG", 371);
      uED = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CONVERSATION_LONG", 372);
      uEE = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CONTACT_LONG", 373);
      uEF = new a("USERINFO_HEAVY_USER_REPORT_TYPE_DB_CHATROOM_LONG", 374);
      uEG = new a("USERINFO_HEAVY_USER_REPORT_TYPE_FAV_DB_SIZE_LONG", 375);
      uEH = new a("USERINFO_MM_LVFETIME_REPORT_PID_INT", 376);
      uEI = new a("USERINFO_MM_LVFETIME_REPORT_LIFETIME_LONG", 377);
      uEJ = new a("USERINFO_MM_LVFETIME_REPORT_MEMORY_PSS_INT", 378);
      uEK = new a("USERINFO_X264_VERSION_INT", 379);
      uEL = new a("USERINFO_SETTING_RECENT_RED_DOT_ID_INT", 380);
      uEM = new a("USERINFO_MY_RED_DOT_WILL_SHOW_ID_INT", 381);
      uEN = new a("USERINFO_MY_RED_DOT_DID_SHOW_ID_INT", 382);
      uEO = new a("USERINFO_SETTING_RED_DOT_WILL_SHOW_ID_INT", 383);
      uEP = new a("USERINFO_SETTING_RED_DOT_DID_SHOW_ID_INT", 384);
      uEQ = new a("USERINFO_PRIVATY_RED_DOT_WILL_SHOW_ID_INT", 385);
      uER = new a("USERINFO_PRIVATY_RED_DOT_DID_SHOW_ID_INT", 386);
      uES = new a("USERINFO_RECENT_RED_DOT_WILL_SHOW_ID_INT", 387);
      uET = new a("USERINFO_RECENT_RED_DOT_DID_SHOW_ID_INT", 388);
      uEU = new a("USERINFO_WEIXIN_ENABLEFPSTOOL_STATE_BOOLEAN", 389);
      uEV = new a("USERINFO_ABOUT_INVOICE_ENTRANCE_BOOLEAN", 390);
      uEW = new a("USERINFO_MUSIO_LAST_SCAN_MUSIC_PIECE_FILE_TIME_LONG", 391);
      uEX = new a("USERINFO_MUSIO_LAST_SCAN_MUSIC_FILE_TIME_LONG", 392);
      uEY = new a("USERINFO_MUSIC_PLAYER_SWITCH_FLAG_INT_SYNC", 393);
      uEZ = new a("USERINFO_MUSIC_SUPPORT_PLAYER_FLAG_SEQUENCE_LONG_SYNC", 394);
      uFa = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_CN_STRING", 395);
      uFb = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_TW_STRING", 396);
      uFc = new a("USERINFO_WEB_SEARCH_CONFIG_ZH_HK_STRING", 397);
      uFd = new a("USERINFO_WEB_SEARCH_CONFIG_EN_STRING", 398);
      uFe = new a("USERINFO_WEB_SEARCH_CONFIG_AR_STRING", 399);
      uFf = new a("USERINFO_WEB_SEARCH_CONFIG_DE_STRING", 400);
      uFg = new a("USERINFO_WEB_SEARCH_CONFIG_DE_DE_STRING", 401);
      uFh = new a("USERINFO_WEB_SEARCH_CONFIG_ES_STRING", 402);
      uFi = new a("USERINFO_WEB_SEARCH_CONFIG_FR_STRING", 403);
      uFj = new a("USERINFO_WEB_SEARCH_CONFIG_HE_STRING", 404);
      uFk = new a("USERINFO_WEB_SEARCH_CONFIG_HI_STRING", 405);
      uFl = new a("USERINFO_WEB_SEARCH_CONFIG_ID_STRING", 406);
      uFm = new a("USERINFO_WEB_SEARCH_CONFIG_IN_STRING", 407);
      uFn = new a("USERINFO_WEB_SEARCH_CONFIG_IT_STRING", 408);
      uFo = new a("USERINFO_WEB_SEARCH_CONFIG_IW_STRING", 409);
      uFp = new a("USERINFO_WEB_SEARCH_CONFIG_JA_STRING", 410);
      uFq = new a("USERINFO_WEB_SEARCH_CONFIG_KO_STRING", 411);
      uFr = new a("USERINFO_WEB_SEARCH_CONFIG_LO_STRING", 412);
      uFs = new a("USERINFO_WEB_SEARCH_CONFIG_MS_STRING", 413);
      uFt = new a("USERINFO_WEB_SEARCH_CONFIG_MY_STRING", 414);
      uFu = new a("USERINFO_WEB_SEARCH_CONFIG_PL_STRING", 415);
      uFv = new a("USERINFO_WEB_SEARCH_CONFIG_PT_STRING", 416);
      uFw = new a("USERINFO_WEB_SEARCH_CONFIG_RU_STRING", 417);
      uFx = new a("USERINFO_WEB_SEARCH_CONFIG_TH_STRING", 418);
      uFy = new a("USERINFO_WEB_SEARCH_CONFIG_TR_STRING", 419);
      uFz = new a("USERINFO_WEB_SEARCH_CONFIG_VI_STRING", 420);
      uFA = new a("USERINFO_CLIENT_SERVER_DIFF_TIME_LONG", 421);
      uFB = new a("USERINFO_MSG_DELAY_STAT_STRING", 422);
      uFC = new a("USERINFO_SET_SUPPORT_WX_CODE_BOOLEAN", 423);
      uFD = new a("USERINFO_TENCENT_MAP_COUNT_INT", 424);
      uFE = new a("USERINFO_CROWDTEST_CLIENT_VERSION_INT", 425);
      uFF = new a("USERINFO_CROWDTEST_APPLY_EXPIRE_LONG", 426);
      uFG = new a("USERINFO_CROWDTEST_APPLY_LINK_STRING", 427);
      uFH = new a("USERINFO_CROWDTEST_FEEDBACK_LINK_STRING", 428);
      uFI = new a("USERINFO_SETTING_PLUGIN_SWITCH_REDDOT_INT", 429);
      uFJ = new a("USERINFO_SETTING_PLUGIN_SWITCH_NAMES_STRING", 430);
      uFK = new a("USERINFO_BACKGROUND_CALC_TIME_LONG", 431);
      uFL = new a("USERINFO_WELAB_LAST_UPDATE_TIME_LONG", 432);
      uFM = new a("USERINFO_WELAB_UPDATE_TIME_INTERVAL_INT", 433);
      uFN = new a("USERINFO_WELAB_SERVER_TIMESTAMP_INT", 434);
      uFO = new a("USERINFO_WELAB_REDPOINT_STRING", 435);
      uFP = new a("USERINFO_WELAB_APP_REDPOINT_STRING", 436);
      uFQ = new a("BUSINESS_OFFLINE_GETMSG_INTERVAL_INT", 437);
      uFR = new a("BUSINESS_OFFLINE_GETMSG_ACK_KEY_STRING", 438);
      uFS = new a("BUSINESS_OFFLINE_GETMSG_MAX_POS_TIME_INT", 439);
      uFT = new a("USERINFO_WALLET_HK_PAY_URL_STRING", 440);
      uFU = new a("USERINFO_SUPPORT_HEVC_VIDEO_INT", 441);
      uFV = new a("USERINFO_HAD_PRELOAD_SIZE_LONG", 442);
      uFW = new a("USERINFO_HAD_PRELOAD_TIME_LONG", 443);
      uFX = new a("USERINFO_C2C_HAD_PRELOAD_COUNT_INT", 444);
      uFY = new a("USERINFO_SNS_HAD_PRELOAD_COUNT_INT", 445);
      uFZ = new a("USERINFO_CHATTING_MONITOR_MAIN_WORDING_STRING_SYNC", 446);
      uGa = new a("USERINFO_CHATTING_MONITOR_MAIN_URL_STRING_SYNC", 447);
      uGb = new a("USERINFO_CHATTING_MONITOR_MAIN_INTERVAL_LONG_SYNC", 448);
      uGc = new a("USERINFO_CHATTING_MONITOR_MAIN_CLOSABLE_BOOLEAN_SYNC", 449);
      uGd = new a("USERINFO_CHATTING_MONITOR_MAIN_AUTOTRIGGER_BOOLEAN_SYNC", 450);
      uGe = new a("USERINFO_CHATTING_BANNER_CLOSED_BOOLEAN_SYNC", 451);
      uGf = new a("USERINFO_MAIN_MONITOR_MAIN_WORDING_STRING_SYNC", 452);
      uGg = new a("USERINFO_MAIN_MONITOR_MAIN_URL_STRING_SYNC", 453);
      uGh = new a("USERINFO_MAIN_MONITOR_MAIN_INTERVAL_LONG_SYNC", 454);
      uGi = new a("USERINFO_MAIN_MONITOR_MAIN_CLOSABLE_BOOLEAN_SYNC", 455);
      uGj = new a("USERINFO_MAIN_MONITOR_MAIN_AUTOTRIGGER_BOOLEAN_SYNC", 456);
      uGk = new a("USERINFO_MAIN_BANNER_CLOSED_BOOLEAN_SYNC", 457);
      uGl = new a("USERINFO_MONITOR_BANNER_MSG_COME_TIME_TICKS_LONG_SYNC", 458);
      uGm = new a("USERINFO_MONITOR_IS_TRIGGERED_BOOLEAN_SYNC", 459);
      uGn = new a("USERINFO_RECENT_LAUNCH_AA_GROUP_STRING_SYNC", 460);
      uGo = new a("USERINFO_WALLET_ENTRY_REDDOT_PUSH_DATE_LONG_SYNC", 461);
      uGp = new a("USERINFO_WALLET_INDEX_MAIDAN_STRING_SYNC", 462);
      uGq = new a("USERINFO_LQT_WALLET_RED_DOT_WORDING_STRING", 463);
      uGr = new a("USERINFO_LQT_WALLET_RED_DOT_INT", 464);
      uGs = new a("USERINFO_LQT_BALANCE_RED_DOT_INT", 465);
      uGt = new a("USERINFO_LQT_LINK_RED_DOT_INT", 466);
      uGu = new a("USERINFO_WEPKG_CHECK_DOWNLOAD_TIME_LONG", 467);
      uGv = new a("USERINFO_FTS_MASTER_DB_VERISON_INT_SYNC", 468);
      uGw = new a("USERINFO_FTS_MASTER_DB_READY_INT_SYNC", 469);
      uGx = new a("USERINFO_FTS_MASTER_DB_CORRUPT_REBUILD_TIME_INT_SYNC", 470);
      uGy = new a("USERINFO_TINKER_BOOTS_CHECK_LAST_TIME_LONG", 471);
      uGz = new a("BUSINESS_OFFLINE_GETMSG_REQ_KEY_STRING", 472);
      uGA = new a("BUSINESS_OFFLINE_GETMSG_PAYMSG_TYPE_INT", 473);
      uGB = new a("BUSINESS_OFFLINE_GETMSG_TRANS_ID_STRING", 474);
      uGC = new a("USERINFO_FTS_DISCOVERY_RED_ID_INT", 475);
      uGD = new a("USERINFO_FTS_DISCOVERY_RED_XML_STRING", 476);
      uGE = new a("NEW_BANDAGE_DATASOURCE_WALLET_MORE_TAB_STRING_SYNC", 477);
      uGF = new a("NEW_BANDAGE_DATASOURCE_WALLET_BANKCARD_STRING_SYNC", 478);
      uGG = new a("NEW_BANDAGE_WATCHER_WALLET_COMMON_STRING_SYNC", 479);
      uGH = new a("USERINFO_WALLET_MORE_TAB_REDDOT_WORDING_STRING_SYNC", 480);
      uGI = new a("USERINFO_WALLET_BANKCARD_SERIAL_STRING_SYNC", 481);
      uGJ = new a("USERINFO_WALLET_F2F_COLLECT_PAY_URL_STRING_SYNC", 482);
      uGK = new a("USERINFO_WALLET_F2F_COLLECT_TRUE_NAME_STRING_SYNC", 483);
      uGL = new a("USERINFO_WALLET_F2F_COLLECT_BOTTOM_MENU_STRING_SYNC", 484);
      uGM = new a("USERINFO_WALLET_F2F_COLLECT_BOTTOM_LEFT_ICON_URL_STRING_SYNC", 485);
      uGN = new a("USERINFO_WALLET_F2F_COLLECT_UPRIGHT_MENU_STRING_SYNC", 486);
      uGO = new a("USERINFO_WALLET_BIND_CARD_MENU_STRING_SYNC", 487);
      uGP = new a("USERINFO_HARDWARE_LAST_UPLOAD_TICKS_LONG_SYNC", 488);
      xob = new a("USERINFO_WALLET_LQT_OPEN_FLAG_INT_SYNC", 489);
      xoc = new a("USERINFO_WALLET_LQT_ENTRY_WORDING_STRING_SYNC", 490);
      uGQ = new a[] { uxv, uxw, uxx, uxy, uxz, uxA, uxB, uxC, uxD, uxE, uxF, uxG, uxH, uxI, uxJ, uxK, uxL, uxM, uxN, uxO, uxP, uxQ, uxR, uxS, uxT, uxU, uxV, uxW, uxX, uxY, uxZ, uya, uyb, uyc, uyd, uye, uyf, uyg, uyh, uyi, uyj, uyk, uyl, uym, uyn, uyo, uyp, uyq, uyr, uys, uyt, uyu, uyv, uyw, uyx, uyy, uyz, uyA, uyB, uyC, uyD, uyE, uyF, uyG, uyH, uyI, uyJ, uyK, uyL, uyM, uyN, uyO, uyP, uyQ, uyR, uyS, uyT, uyU, uyV, uyW, uyX, uyY, uyZ, uza, uzb, uzc, uzd, uze, uzf, uzg, uzh, uzi, uzj, uzk, uzl, uzm, uzn, uzo, uzp, uzq, uzr, uzs, uzt, uzu, uzv, uzw, uzx, uzy, uzz, uzA, uzB, uzC, uzD, uzE, uzF, uzG, uzH, uzI, uzJ, uzK, uzL, uzM, uzN, uzO, uzP, uzQ, uzR, uzS, uzT, uzU, uzV, uzW, uzX, uzY, uzZ, uAa, uAb, uAc, uAd, uAe, uAf, uAg, uAh, uAi, uAj, uAk, uAl, uAm, uAn, uAo, uAp, uAq, uAr, uAs, uAt, uAu, uAv, uAw, uAx, uAy, uAz, uAA, uAB, uAC, uAD, uAE, uAF, uAG, uAH, uAI, uAJ, uAK, uAL, uAM, uAN, uAO, uAP, uAQ, uAR, uAS, uAT, uAU, uAV, uAW, uAX, uAY, uAZ, uBa, uBb, uBc, uBd, uBe, uBf, uBg, uBh, uBi, uBj, uBk, uBl, uBm, uBn, uBo, uBp, uBq, uBr, uBs, uBt, uBu, uBv, uBw, uBx, uBy, uBz, uBA, uBB, uBC, uBD, uBE, uBF, uBG, uBH, uBI, uBJ, uBK, uBL, uBM, uBN, uBO, uBP, uBQ, uBR, uBS, uBT, uBU, uBV, uBW, uBX, uBY, uBZ, uCa, uCb, uCc, uCd, uCe, uCf, uCg, uCh, uCi, uCj, uCk, uCl, uCm, uCn, uCo, uCp, uCq, uCr, uCs, uCt, uCu, uCv, uCw, uCx, uCy, uCz, uCA, uCB, uCC, uCD, uCE, uCF, uCG, uCH, uCI, uCJ, uCK, uCL, uCM, uCN, uCO, uCP, uCQ, uCR, uCS, uCT, uCU, uCV, uCW, uCX, uCY, uCZ, uDa, uDb, uDc, uDd, uDe, uDf, uDg, uDh, uDi, uDj, uDk, uDl, uDm, uDn, uDo, uDp, uDq, uDr, uDs, uDt, uDu, uDv, uDw, uDx, uDy, uDz, uDA, uDB, uDC, uDD, uDE, uDF, uDG, uDH, uDI, uDJ, uDK, uDL, uDM, uDN, uDO, uDP, uDQ, uDR, uDS, uDT, uDU, uDV, uDW, uDX, uDY, uDZ, uEa, uEb, uEc, uEd, uEe, uEf, uEg, uEh, uEi, uEj, uEk, uEl, uEm, uEn, uEo, uEp, uEq, uEr, uEs, uEt, uEu, uEv, uEw, uEx, uEy, uEz, uEA, uEB, uEC, uED, uEE, uEF, uEG, uEH, uEI, uEJ, uEK, uEL, uEM, uEN, uEO, uEP, uEQ, uER, uES, uET, uEU, uEV, uEW, uEX, uEY, uEZ, uFa, uFb, uFc, uFd, uFe, uFf, uFg, uFh, uFi, uFj, uFk, uFl, uFm, uFn, uFo, uFp, uFq, uFr, uFs, uFt, uFu, uFv, uFw, uFx, uFy, uFz, uFA, uFB, uFC, uFD, uFE, uFF, uFG, uFH, uFI, uFJ, uFK, uFL, uFM, uFN, uFO, uFP, uFQ, uFR, uFS, uFT, uFU, uFV, uFW, uFX, uFY, uFZ, uGa, uGb, uGc, uGd, uGe, uGf, uGg, uGh, uGi, uGj, uGk, uGl, uGm, uGn, uGo, uGp, uGq, uGr, uGs, uGt, uGu, uGv, uGw, uGx, uGy, uGz, uGA, uGB, uGC, uGD, uGE, uGF, uGG, uGH, uGI, uGJ, uGK, uGL, uGM, uGN, uGO, uGP, xob, xoc };
      GMTrace.o(13535992086528L, 100851);
    }
    
    private a()
    {
      GMTrace.i(13535857868800L, 100850);
      GMTrace.o(13535857868800L, 100850);
    }
  }
}


/* Location:              /home/chengjian/weinxin/weinxin_1100/classes.jar!/com/tencent/mm/storage/w.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */