package com.google.android.finsky.ag;

import java.util.HashSet;

public final class c
{
  public static final q A;
  public static final q B;
  public static final q C;
  public static final q D;
  public static final q E;
  public static final q F;
  public static final q G;
  public static final q H;
  public static final q I;
  public static final q J;
  public static final q K;
  public static final q L;
  public static final q M;
  public static final q N;
  public static final q O;
  public static final p P;
  public static final p Q;
  public static final p R;
  public static final q S;
  public static final q T;
  public static final q U;
  public static final q V;
  public static final q W;
  public static final q X;
  public static final q Y;
  public static final q Z;
  public static final p a;
  public static final p aA;
  public static final p aB;
  public static final p aC;
  public static final p aD;
  public static final p aE;
  public static final q aF;
  public static final q aG;
  public static final p aH;
  public static final q aI;
  public static final p aJ;
  public static final q aK;
  public static final q aL;
  public static final p aM;
  public static final q aN;
  public static final q aO;
  public static final q aP;
  public static final q aQ;
  public static final q aR;
  public static final p aS;
  public static final p aT;
  public static final q aU;
  public static final q aV;
  public static final q aW;
  public static final p aX;
  public static final p aY;
  public static final q aZ;
  public static final q aa;
  public static final p ab;
  public static final q ac;
  public static final p ad;
  public static final p ae;
  public static final p af;
  public static final q ag;
  public static final q ah;
  public static final q ai;
  public static final q aj;
  public static final q ak;
  public static final p al;
  public static final p am;
  public static final p an;
  public static final q ao;
  public static final q ap;
  public static final q aq;
  public static final q ar;
  public static final q as;
  public static final q at;
  public static final q au;
  public static final q av;
  public static final p aw;
  public static final q ax;
  public static final q ay;
  public static final q az;
  public static final q b;
  public static final q bA;
  public static final q bB;
  public static final f bC;
  public static final q bD;
  public static final q bE;
  public static final q bF;
  public static final q bG;
  public static final q bH;
  public static final p bI;
  public static final p bJ;
  public static final q bK;
  public static final q bL;
  public static final q bM;
  public static final p bN;
  public static final p bO;
  public static final q bP;
  public static final q bQ;
  public static final p bR;
  public static final p bS;
  public static final p bT;
  public static final q bU;
  public static final q bV;
  public static final p bW;
  public static final p bX;
  public static final p bY;
  public static final q bZ;
  public static final q ba;
  public static final q bb;
  public static final q bc;
  public static final q bd;
  public static final p be;
  public static final q bf;
  public static final p bg;
  public static final q bh;
  public static final p bi;
  public static final q bj;
  public static final q bk;
  public static final p bl;
  public static final q bm;
  public static final q bn;
  public static final q bo;
  public static final p bp;
  public static final p bq;
  public static final p br;
  public static final p bs;
  public static final p bt;
  public static final p bu;
  public static final p bv;
  public static final p bw;
  public static final q bx;
  public static final q by;
  public static final q bz;
  public static final p c;
  public static final q ca;
  public static final q cb;
  public static final q cc;
  public static final q cd;
  public static final q ce;
  public static final p cf;
  public static final q cg;
  private static final p ch;
  public static final p d;
  public static final p e;
  public static final p f;
  public static final p g;
  public static final p h;
  public static final p i;
  public static final p j;
  public static final p k;
  public static final q l;
  public static final q m;
  public static final q n;
  public static final q o;
  public static final q p;
  public static final q q;
  public static final q r;
  public static final q s;
  public static final q t;
  public static final q u;
  public static final p v;
  public static final p w;
  public static final p x;
  public static final q y;
  public static final q z;
  
  static
  {
    Object localObject1 = new f("finsky");
    bC = (f)localObject1;
    Integer localInteger = Integer.valueOf(-1);
    ce = ((f)localObject1).a("last_version_code", localInteger);
    B = bC.a("content-filter-level", localInteger);
    C = bC.a("content-filters-2", "");
    v = bC.b("cached-content-filters-3", null);
    bI = bC.b("server-logs-cookie", null);
    D = bC.a("content-filters-selections", null);
    Object localObject2 = bC;
    localObject1 = Boolean.valueOf(false);
    ((f)localObject2).a("content-filter-2-visited-once", (Boolean)localObject1);
    bC.a("internal-enabled-permissive-split-mode-for-test", (Boolean)localObject1);
    bC.a("internal-always-show-split-ack-dialog-for-test", (Boolean)localObject1);
    bf = bC.a("pending-language-splits", (Boolean)localObject1);
    G = bC.a("account", null);
    E = bC.a("pin_code", null);
    Object localObject3 = bC;
    localObject2 = Long.valueOf(0L);
    aI = ((f)localObject3).a("last-device-feature-logged-timestamp-ms", (Long)localObject2);
    Object localObject4 = bC;
    localObject3 = Integer.valueOf(0);
    aa = ((f)localObject4).a("dynamic-config-hash", (Integer)localObject3);
    R = bC.b("device-config-token", null);
    ar = bC.a("gcm-registration-id-on-server", null);
    H = bC.a("dailyhygiene-failed", (Integer)localObject3);
    f localf = bC;
    localObject4 = Long.valueOf(-1L);
    M = localf.a("dailyhygiene-lastsuccess", (Long)localObject4);
    K = bC.a("dailyhygiene-lastforeground", (Long)localObject4);
    ay = bC.a("hygiene-tasks-offline-device-state-handled", (Boolean)localObject1);
    az = bC.a("hygiene-tasks-unath-device-state-handled", (Boolean)localObject1);
    ax = bC.a("hygiene-tasks-authenticated-device-state-handled", (Boolean)localObject1);
    L = bC.a("dailyhygiene-last-version", localInteger);
    J = bC.a("dailyhygiene-last-android-version", null);
    I = bC.a("dailyhygiene-holdoff-complete", (Boolean)localObject1);
    p = bC.a("appFreshness-last-logging", (Long)localObject2);
    bB = bC.a("routinehygiene-window-start-ms", (Long)localObject2);
    localf = bC;
    Boolean localBoolean = Boolean.valueOf(true);
    r = localf.a("auto_update_enabled", localBoolean);
    s = bC.a("update_over_wifi_only", localBoolean);
    Y = bC.a("dfe-notification-pending-acks", null);
    aL = bC.a("last-replicated-database-version", localInteger);
    bw = bC.b("replicated-system-apps-hash", (Integer)localObject3);
    e = bC.b("client-accepted-last-tos-token", "");
    z = bC.a("no-conn-noti-req", (Boolean)localObject1);
    aY = bC.b("opt-in-marketing-emails", null);
    aX = bC.b("opt-in-dialog-first-attempt", null);
    aD = bC.b("instant-apps-tos-accepted", null);
    aE = bC.b("instant-apps-tos-accepted-ms", (Long)localObject2);
    a = bC.b("last-tos-token", "");
    b = bC.a("accepted-anti-malware-consent", (Boolean)localObject1);
    o = bC.a("anti-malware-consent-model", "PreferenceConsent");
    cb = bC.a("verify-installed-apps-last-success-ms", (Long)localObject2);
    ac = bC.a("enable-play-protect-notification-last-action-ms", (Long)localObject2);
    bZ = bC.a("verify-install-packages-has-pha", (Boolean)localObject1);
    ca = bC.a("verify-install-packages-has-offline-download", (Boolean)localObject1);
    cc = bC.a("verify-installed-apps-lite-last-success-ms", (Long)localObject2);
    bD = bC.a("safety-net-id-cached-value", null);
    F = bC.a("corruption-experiment-day-of-week", (Integer)localObject3);
    bM = bC.a("sim-hash-apk-day-of-week", (Integer)localObject3);
    aP = bC.a("last-vole-status-safe", (Boolean)localObject1);
    aQ = bC.a("last-vole-status-timestamp-ms", (Long)localObject2);
    aO = bC.a("last-verify-apps-event", (Integer)localObject3);
    bv = bC.b("replicated-account-apps-hash:", (Integer)localObject3);
    f = bC.b("has-fop", null);
    g = bC.b("has-fop-last-update-ms", (Long)localObject2);
    bt = bC.b("prompt-for-fop-num-snoozed", (Integer)localObject3);
    h = bC.b("waa-enabled", null);
    i = bC.b("account-payments-setup-notification-sent", (Boolean)localObject1);
    bq = bC.b("prompt-for-fop-last-snooze-timestamp-ms", (Long)localObject2);
    br = bC.b("prompt-for-fop-num-dialog-impressions", (Integer)localObject3);
    bs = bC.b("prompt-for-fop-num-fop-selector-impressions", (Integer)localObject3);
    bp = bC.b("prompt-for-fop-fop-added", (Boolean)localObject1);
    aJ = bC.b("last-gaia-auth-timestamp", (Long)localObject2);
    bR = bC.b("target-list", null);
    bS = bC.b("target-override-list", null);
    bJ = bC.b("server-target-override-list", null);
    ch = bC.b("server_token:", "");
    bk = bC.a("preregistration-released-docs", null);
    bl = bC.b("preregistration-released-ms", (Long)localObject2);
    d = bC.b("accepted-public-reviews-disclaimer", (Boolean)localObject1);
    c = bC.b("accepted-plus-reviews", (Boolean)localObject1);
    bP = bC.a("successful-update-notification-app-list", "");
    aN = bC.a("last-update-avail-notification-timestamp-ms", (Long)localObject2);
    t = bC.a("auto-update-discovered-at-ms", (Long)localObject2);
    bC.a("internal-enable-self-update-on-debug-build", (Boolean)localObject1);
    bC.a("unauthenticated-on-debug-build", (Boolean)localObject1);
    bC.a("daily-hygiene-disable-on-debug-build", (Boolean)localObject1);
    bC.a("wear-known-devices", null);
    bC.b("wear-device-last-seen", (Long)localObject2);
    cf = bC.b("wear-device-config-token", null);
    bT = bC.b("toc-cookie", null);
    P = bC.b("debug-locale-override", null);
    O = bC.a("debug-force-dapper-trace", (Boolean)localObject1);
    Q = bC.b("debug-overrides", null);
    bW = bC.b("user-settings-cache", null);
    bX = bC.b("user-settings-cache-dirty-type", null);
    bY = bC.b("user-settings-consistency-tokens", null);
    m = bC.a("adid-cached-value", null);
    n = bC.a("adid-limit-tracking-cached-value", null);
    l = bC.a("adid-cached-timestamp-ms", (Long)localObject2);
    aR = bC.a("logs-flush-schedule-expired-timestamp", (Long)localObject2);
    au = bC.a("has-stale-process-stable-targets", (Boolean)localObject1);
    as = bC.a("has-cache-affecting-process-stable-target-changed", localBoolean);
    av = bC.a("has-stale-process-stable-experiment-flags", (Boolean)localObject1);
    at = bC.a("has-cache-affecting-process-stable-experiment-flags-changed", (Boolean)localObject1);
    ao = bC.a("family-sharing-education-card-shown-count", (Integer)localObject3);
    ak = bC.a("family-library-notifications-education-card-shown-count", (Integer)localObject3);
    am = bC.b("family-paused-education-card-dimissal-time-ms", (Long)localObject2);
    al = bC.b("family-music-upgrade-prompt-shown-count", (Integer)localObject3);
    ap = bC.a("file-by-file-last-check-fingerprint", null);
    aq = bC.a("file-by-file-last-check-result", (Boolean)localObject1);
    bC.a("internal-enabled-test-mode", (Boolean)localObject1);
    bC.a("internal-allow-admob-override", (Boolean)localObject1);
    T = bC.a("device-google-certified", null);
    S = bC.a("device-google-certified-basic-integrity", null);
    U = bC.a("device-google-certified-key", "");
    ad = bC.b("enterprise-acl-consistency-token", null);
    ae = bC.b("enterprise-acl-consistency-token-timestamp-ms", (Long)localObject2);
    af = bC.b("enterprise-acl-consistency-token-ttl-ms", (Long)localObject2);
    aG = bC.a("jpkr_mini_top_chart_tooltip_shown", (Boolean)localObject1);
    bj = bC.a("preregistrable-games-rewards-tooltip-shown", (Boolean)localObject1);
    bA = bC.a("reviews-policy-tooltip-shown", (Boolean)localObject1);
    A = bC.a("content_filter_consistency_token", null);
    an = bC.b("family_remote_escalation_consistency_token", null);
    aw = bC.b("home-url", null);
    cg = bC.a("wear-paired-device", (Integer)localObject3);
    aU = bC.a("myapps-installed-cluster-sort", (Integer)localObject3);
    aV = bC.a("myapps-library-cluster-sort", null);
    N = bC.a("data-plan-response-cache", null);
    bu = bC.b("remote_escalation_notification_update_time", (Long)localObject2);
    bU = bC.a("uninstall-manager-selection-sort", Integer.valueOf(5));
    bV = bC.a("uninstall-manager-show-callout", localBoolean);
    aj = bC.a("estimated-backed-up-photos-size-bytes", (Long)localObject2);
    ai = bC.a("estimated-backed-up-photos-count", (Integer)localObject3);
    u = bC.a("backed-up-photos-timestamp-ms", (Long)localObject2);
    Z = bC.a("directed-restore-started", (Boolean)localObject1);
    ab = bC.b("early-update-skip-package", (Boolean)localObject1);
    bQ = bC.a("system-backup-ready", (Boolean)localObject1);
    bc = bC.a("pai-unauth-acquire-needed", (Boolean)localObject1);
    bb = bC.a("pai-unauth-acquire-attempts", (Integer)localObject3);
    ba = bC.a("pai-required-installs-triggered", (Boolean)localObject1);
    aZ = bC.a("pai-deferred-notification-supported", (Boolean)localObject1);
    bh = bC.a("vpa-selection-triggered", (Boolean)localObject1);
    bz = bC.a("restore-success-count", (Integer)localObject3);
    bx = bC.a("restore-failure-count", (Integer)localObject3);
    by = bC.a("restore_start_recorded", (Boolean)localObject1);
    aA = bC.b("install-holdoff-calls", "");
    bH = bC.a("scheduler_last_wakeup_elapsed_realtime_ms", (Long)localObject4);
    bG = bC.a("scheduler_last_odyssey_logged_elapsed_real_time_ms", (Long)localObject4);
    bF = bC.a("scheduler_phonesky_version_code", localInteger);
    x = bC.b("catch-abandonment-dialog-count", (Integer)localObject3);
    aH = bC.b("last-catch-abandonment-dialog-timestamp-ms", (Long)localObject2);
    aT = bC.b("my-apps-assist-card-dismissed-timestamp", (Long)localObject2);
    aS = bC.b("my-apps-assist-card-dismissed-count", (Integer)localObject3);
    aW = bC.a("my-apps-security-dismissed-pha", null);
    cd = bC.a("verify-parent-enabled", localBoolean);
    bi = bC.b("prereg-opt-in-checkbox-shown", (Boolean)localObject1);
    k = bC.b("timestamp-until-which-acquire-caching-is-disabled", (Long)localObject2);
    X = bC.a("device-wide-unknown-source-block-enabled", (Boolean)localObject1);
    aB = bC.b("instant-apps-language-included-in-tos", (Boolean)localObject1);
    aC = bC.b("instant-apps-opt-in-state", localInteger);
    be = bC.b("pending-instant-apps-operation-", localInteger);
    j = bC.b("account-play-country", "");
    bn = bC.a("previous-store-app-data", null);
    y = bC.a("chrome-enabled-on-managed-profile-on-o", (Boolean)localObject1);
    bo = new i(bC, "previously-notified-subscriber-id", new HashSet());
    q = new i(bC, "assist-cards-dismissed-tokens", new HashSet());
    w = bC.b("cached-unread-notification-count", (Integer)localObject3);
    bm = bC.a("previous-notification-android-system-setting", localInteger);
    bN = bC.b("sticky-home-url-key", localInteger);
    bO = bC.b("sticky-home-urls", null);
    aM = bC.b("last-sticky-tab-usage-timestamp-ms", (Long)localObject2);
    bd = bC.a("pause-expected-during-recovery", (Boolean)localObject1);
    bC.a("print_latency_events_to_screen", (Boolean)localObject1);
    aF = bC.a("instant-apps-try-now-tooltip-shown-count", (Integer)localObject3);
    aK = bC.a("last-logged-launcher-icon-count", localInteger);
    ag = bC.a("enterprise-daily-hygiene-holdoff-wait-complete", (Boolean)localObject1);
    ah = bC.a("enterprise-daily-hygiene-holdoff-wait-start-timestamp-ms", (Long)localObject2);
    bC.b("last-tier-when-loyalty-tier-info-cluster-dismissed", (Integer)localObject3);
    V = bC.a("device-settings-cache", null);
    W = bC.a("device-settings-cache-timestamp-millis", (Long)localObject2);
    bL = bC.a("show-got-it-card-new-review", localBoolean);
    bK = bC.a("show-got-it-card-edit-review", localBoolean);
    bE = bC.a("saved_override_search_string", "");
    bC.b("snooze-action-count", (Integer)localObject3);
    bC.b("snooze-last-action-time", (Long)localObject2);
    bg = bC.b("iab_account", "");
    bC.b("transactional-points-balance-on-last-loyalty-home-visit:", (Long)localObject4);
  }
  
  public static q a(String paramString1, String paramString2)
  {
    p localp = ch;
    StringBuilder localStringBuilder = new StringBuilder(String.valueOf(paramString1).length() + 1 + String.valueOf(paramString2).length());
    localStringBuilder.append(paramString1);
    localStringBuilder.append(":");
    localStringBuilder.append(paramString2);
    return localp.b(localStringBuilder.toString());
  }
}


/* Location:              /home/chengjian/CM_test/gp/apk/a.jar!/com/google/android/finsky/ag/c.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */