package com.google.android.finsky.ag;

import android.text.TextUtils;
import com.google.android.finsky.utils.FinskyLog;
import com.google.android.finsky.utils.at;
import com.google.android.play.utils.b.a;
import java.util.concurrent.TimeUnit;

public final class d
{
  public static final a A;
  public static final a B;
  public static final a C;
  public static final a D;
  public static final a E;
  public static final a F;
  public static final a G;
  public static final a H;
  public static final a I;
  public static final a J;
  public static final a K;
  public static final a L;
  public static final a M;
  public static final a N;
  public static final a O;
  public static final a P;
  public static final a Q;
  public static final a R;
  public static final a S;
  public static final a T;
  public static final a U;
  public static final a V;
  public static final a W;
  public static final a X;
  public static final a Y;
  public static final a Z;
  public static final String[] a = { "android_id", "finsky.", "vending_", "logging_id2", "market_client_id" };
  public static final a aA;
  public static final a aB;
  public static final a aC;
  public static final a aD;
  public static final a aE;
  public static final a aF;
  public static final a aG;
  public static final a aH;
  public static final a aI;
  public static final a aJ;
  public static final a aK;
  public static final a aL;
  public static final a aM;
  public static final a aN;
  public static final a aO;
  public static final a aP;
  public static final a aQ;
  public static final a aR;
  public static final a aS;
  public static final a aT;
  public static final a aU;
  public static final a aV;
  public static final a aW;
  public static final a aX;
  public static final a aY;
  public static final a aZ;
  public static final a aa;
  public static final a ab;
  public static final a ac;
  public static final a ad;
  public static final a ae;
  public static final a af;
  public static final a ag;
  public static final a ah;
  public static final a ai;
  public static final a aj;
  public static final a ak;
  public static final a al;
  public static final a am;
  public static final a an;
  public static final a ao;
  public static final a ap;
  public static final a aq;
  public static final a ar;
  public static final a as;
  public static final a at;
  public static final a au;
  public static final a av;
  public static final a aw;
  public static final a ax;
  public static final a ay;
  public static final a az;
  public static final a b;
  public static final a bA;
  public static final a bB;
  public static final a bC;
  public static final a bD = a.a("finsky.device_promotion_help_url", "https://support.google.com/googleplay/?hl=en#topic=3364260");
  public static final a bE;
  public static final a bF;
  public static final a bG;
  public static final a bH;
  public static final a bI;
  public static final a bJ;
  public static final a bK;
  public static final a bL;
  public static final a bM;
  public static final a bN;
  public static final a bO;
  public static final a bP;
  public static final a bQ;
  public static final a bR;
  public static final a bS;
  public static final a bT;
  public static final a bU;
  public static final a bV;
  public static final a bW;
  public static final a bX;
  public static final a bY;
  public static final a bZ;
  public static final a ba;
  public static final a bb;
  public static final a bc;
  public static final a bd;
  public static final a be;
  public static final a bf;
  public static final a bg;
  public static final a bh;
  public static final a bi;
  public static final a bj;
  public static final a bk;
  public static final a bl;
  public static final a bm;
  public static final a bn;
  public static final a bo;
  public static final a bp;
  public static final a bq;
  public static final a br;
  public static final a bs;
  public static final a bt;
  public static final a bu;
  public static final a bv;
  public static final a bw;
  public static final a bx;
  public static final a by;
  public static final a bz;
  public static final a c;
  public static final a cA;
  public static final a cB;
  public static final a cC;
  public static final a cD;
  public static final a cE;
  public static final a cF;
  public static final a cG;
  public static final a cH;
  public static final a cI;
  public static final a cJ;
  public static final a cK;
  public static final a cL;
  public static final a cM;
  public static final a cN;
  public static final a cO;
  public static final a cP;
  public static final a cQ;
  public static final a cR;
  public static final a cS;
  public static final a cT;
  public static final a cU;
  public static final a cV;
  public static final a cW;
  public static final a cX;
  public static final a cY;
  public static final a cZ;
  public static final a ca;
  public static final a cb;
  public static final a cc;
  public static final a cd;
  public static final a ce;
  public static final a cf;
  public static final a cg;
  public static final a ch;
  public static final a ci;
  public static final a cj;
  public static final a ck;
  public static final a cl;
  public static final a cm;
  public static final a cn;
  public static final a co;
  public static final a cp;
  public static final a cq;
  public static final a cr;
  public static final a cs;
  public static final a ct;
  public static final a cu;
  public static final a cv;
  public static final a cw;
  public static final a cx;
  public static final a cy;
  public static final a cz;
  public static final a d;
  public static final a dA;
  public static final a dB;
  public static final a dC;
  public static final a dD;
  public static final a dE;
  public static final a dF;
  public static final a dG;
  public static final a dH;
  public static final a dI;
  public static final a dJ;
  public static final a dK;
  public static final a dL;
  public static final a dM;
  public static final a dN;
  public static final a dO;
  public static final a dP;
  public static final a dQ;
  public static final a dR;
  public static final a dS;
  public static final a dT;
  public static final a dU;
  public static final a dV;
  public static final a dW;
  public static final a dX;
  public static final a dY;
  public static final a dZ;
  public static final a da;
  public static final a db;
  public static final a dc;
  public static final a dd;
  public static final a de;
  public static final a df;
  public static final a dg;
  public static final a dh;
  public static final a di;
  public static final a dj;
  public static final a dk;
  public static final a dl;
  public static final a dm;
  public static final a dn;
  public static final a jdField_do;
  public static final a dp;
  public static final a dq;
  public static final a dr;
  public static final a ds;
  public static final a dt;
  public static final a du;
  public static final a dv;
  public static final a dw;
  public static final a dx;
  public static final a dy;
  public static final a dz;
  public static final a e;
  public static final a eA;
  public static final a eB;
  public static final a eC;
  public static final a eD;
  public static final a eE;
  public static final a eF;
  public static final a eG;
  public static final a eH;
  public static final a eI;
  public static final a eJ;
  public static final a eK;
  public static final a eL;
  public static final a eM;
  public static final a eN;
  public static final a eO;
  public static final a eP;
  public static final a eQ;
  public static final a eR;
  public static final a eS;
  public static final a eT;
  public static final a eU;
  public static final a eV;
  public static final a eW;
  public static final a eX;
  public static final a eY;
  public static final a eZ;
  public static final a ea;
  public static final a eb;
  public static final a ec;
  public static final a ed;
  public static final a ee;
  public static final a ef;
  public static final a eg;
  public static final a eh;
  public static final a ei;
  public static final a ej;
  public static final a ek;
  public static final a el;
  public static final a em;
  public static final a en;
  public static final a eo;
  public static final a ep;
  public static final a eq;
  public static final a er;
  public static final a es;
  public static final a et;
  public static final a eu;
  public static final a ev;
  public static final a ew;
  public static final a ex;
  public static final a ey;
  public static final a ez;
  public static final a f;
  public static final a fA;
  public static final a fB;
  public static final a fC;
  public static final a fD;
  public static final a fE;
  public static final a fF;
  public static final a fG;
  public static final a fH;
  public static final a fI;
  public static final a fJ;
  public static final a fK;
  public static final a fL;
  public static final a fM;
  public static final a fN;
  public static final a fO;
  public static final a fP;
  public static final a fQ;
  public static final a fR;
  public static final a fS;
  public static final a fT;
  public static final a fU;
  public static final a fV;
  public static final a fW;
  public static final a fX;
  public static final a fY;
  public static final a fZ;
  public static final a fa;
  public static final a fb;
  public static final a fc;
  public static final a fd;
  public static final a fe;
  public static final a ff;
  public static final a fg;
  public static final a fh;
  public static final a fi;
  public static final a fj;
  public static final a fk;
  public static final a fl;
  public static final a fm;
  public static final a fn;
  public static final a fo;
  public static final a fp;
  public static final a fq;
  public static final a fr;
  public static final a fs;
  public static final a ft;
  public static final a fu;
  public static final a fv;
  public static final a fw;
  public static final a fx;
  public static final a fy;
  public static final a fz;
  public static final a g;
  public static final a gA;
  public static final a gB;
  public static final a gC;
  public static final a gD;
  public static final a gE;
  public static final a gF;
  public static final a gG;
  public static final a gH;
  public static final a gI;
  public static final a gJ;
  public static final a gK;
  public static final a gL;
  public static final a gM;
  public static final a gN;
  public static final a gO;
  public static final a gP;
  public static final a gQ;
  public static final a gR;
  public static final a gS;
  public static final a gT;
  public static final a gU;
  public static final a gV;
  public static final a gW;
  public static final a gX;
  public static final a gY;
  public static final a gZ;
  public static final a ga;
  public static final a gb;
  public static final a gc;
  public static final a gd;
  public static final a ge;
  public static final a gf;
  public static final a gg;
  public static final a gh;
  public static final a gi;
  public static final a gj;
  public static final a gk;
  public static final a gl;
  public static final a gm;
  public static final a gn;
  public static final a go;
  public static final a gp;
  public static final a gq;
  public static final a gr;
  public static final a gs;
  public static final a gt;
  public static final a gu;
  public static final a gv;
  public static final a gw;
  public static final a gx;
  public static final a gy;
  public static final a gz;
  public static final a h;
  public static final a hA;
  public static final a hB;
  public static final a hC;
  public static final a hD;
  public static final a hE;
  public static final a hF;
  public static final a hG;
  public static final a hH;
  public static final a hI;
  public static final a hJ;
  public static final a hK;
  public static final a hL;
  public static final a hM;
  public static final a hN;
  public static final a hO;
  public static final a hP;
  public static final a hQ;
  public static final a hR;
  public static final a hS;
  public static final a hT;
  public static final a hU;
  public static final a hV;
  public static final a hW;
  public static final a hX;
  public static final a hY;
  public static final a hZ;
  public static final a ha;
  public static final a hb;
  public static final a hc;
  public static final a hd;
  public static final a he;
  public static final a hf;
  public static final a hg;
  public static final a hh;
  public static final a hi;
  public static final a hj;
  public static final a hk;
  public static final a hl;
  public static final a hm;
  public static final a hn;
  public static final a ho;
  public static final a hp;
  public static final a hq;
  public static final a hr;
  public static final a hs;
  public static final a ht;
  public static final a hu;
  public static final a hv;
  public static final a hw;
  public static final a hx;
  public static final a hy;
  public static final a hz;
  public static final a i;
  public static final a iA;
  public static final a iB;
  public static final a iC;
  public static final a iD;
  public static final a iE;
  public static final a iF;
  public static final a iG;
  public static final a iH;
  public static final a iI;
  public static final a iJ;
  public static final a iK;
  public static final a iL;
  public static final a iM;
  public static final a iN;
  public static final a iO;
  public static final a iP;
  public static final a iQ;
  public static final a iR;
  public static final a iS;
  public static final a iT;
  public static final a iU;
  public static final a iV;
  public static final a iW;
  public static final a iX;
  public static final a iY;
  public static final a iZ;
  public static final a ia;
  public static final a ib;
  public static final a ic;
  public static final a id;
  public static final a ie;
  public static final a jdField_if;
  public static final a ig;
  public static final a ih;
  public static final a ii;
  public static final a ij;
  public static final a ik;
  public static final a il;
  public static final a im;
  public static final a in;
  public static final a io;
  public static final a ip;
  public static final a iq;
  public static final a ir;
  public static final a is;
  public static final a it;
  public static final a iu;
  public static final a iv;
  public static final a iw;
  public static final a ix;
  public static final a iy;
  public static final a iz;
  public static final a j;
  public static final a jA;
  public static final a jB;
  public static final a jC;
  public static final a jD;
  public static final a jE;
  public static final a jF;
  public static final a jG;
  public static final a jH;
  public static final a jI;
  public static final a jJ;
  public static final a jK;
  public static final a jL;
  public static final a jM;
  public static final a jN;
  public static final a jO;
  public static final a jP;
  public static final a jQ;
  public static final a jR;
  public static final a jS;
  public static final a jT;
  public static final a jU;
  public static final a jV;
  public static final a jW;
  public static final a jX;
  public static final a jY;
  public static final a jZ;
  public static final a ja;
  public static final a jb;
  public static final a jc;
  public static final a jd;
  public static final a je;
  public static final a jf;
  public static final a jg;
  public static final a jh;
  public static final a ji;
  public static final a jj;
  public static final a jk;
  public static final a jl;
  public static final a jm;
  public static final a jn;
  public static final a jo;
  public static final a jp;
  public static final a jq;
  public static final a jr;
  public static final a js;
  public static final a jt;
  public static final a ju;
  public static final a jv;
  public static final a jw;
  public static final a jx;
  public static final a jy;
  public static final a jz;
  public static final a k;
  public static final a kA;
  public static final a kB;
  public static final a kC;
  public static final a kD;
  public static final a kE;
  public static final a kF;
  public static final a kG;
  public static final a kH;
  public static final a kI;
  public static final a kJ;
  public static final a kK;
  public static final a kL;
  public static final a kM;
  public static final a kN;
  public static final a kO;
  public static final a kP;
  public static final a kQ;
  public static final a kR;
  public static final a kS;
  public static final a kT;
  public static final a kU;
  public static final a kV;
  public static final a kW;
  public static final a kX;
  public static final a kY;
  public static final a kZ;
  public static final a ka;
  public static final a kb;
  public static final a kc;
  public static final a kd;
  public static final a ke;
  public static final a kf;
  public static final a kg;
  public static final a kh;
  public static final a ki;
  public static final a kj;
  public static final a kk;
  public static final a kl;
  public static final a km;
  public static final a kn;
  public static final a ko;
  public static final a kp;
  public static final a kq;
  public static final a kr;
  public static final a ks;
  public static final a kt;
  public static final a ku;
  public static final a kv;
  public static final a kw;
  public static final a kx;
  public static final a ky;
  public static final a kz;
  public static final a l;
  public static final a lA;
  public static final a lB;
  public static final a lC;
  public static final a lD;
  private static a lE;
  public static final a la;
  public static final a lb;
  public static final a lc;
  public static final a ld;
  public static final a le;
  public static final a lf;
  public static final a lg;
  public static final a lh;
  public static final a li;
  public static final a lj;
  public static final a lk;
  public static final a ll;
  public static final a lm;
  public static final a ln;
  public static final a lo;
  public static final a lp;
  public static final a lq;
  public static final a lr;
  public static final a ls;
  public static final a lt;
  public static final a lu;
  public static final a lv;
  public static final a lw;
  public static final a lx;
  public static final a ly;
  public static final a lz;
  public static final a m;
  public static final a n;
  public static final a o;
  public static final a p;
  public static final a q;
  public static final a r;
  public static final a s;
  public static final a t;
  public static final a u;
  public static final a v;
  public static final a w;
  public static final a x;
  public static final a y;
  public static final a z;
  
  static
  {
    Boolean localBoolean1 = Boolean.valueOf(true);
    a.a("finsky.leanback_gamepad_warning_badge_enabled", localBoolean1);
    a.a("finsky.leanback_gamepad_warning_confirm", localBoolean1);
    a.a("finsky.leanback_home_tab_url", "browseStream?esp=EAdiLAoqCiRuZXdfaG9tZV9jYW52YXNfZmVhdHVyZWRfQVBQTElDQVRJT04QBxgD&n=5&o=0");
    a.a("finsky.leanback_games_tab_url", "browseStream?esp=EAdiJQojCh1uZXdfaG9tZV9jYW52YXNfZmVhdHVyZWRfR0FNRRAHGAM%3D&n=5&o=0");
    fc = a.a("finsky.low_ram_threshold", Long.valueOf(at.d.a(512L)));
    Integer localInteger1 = Integer.valueOf(3);
    ff = a.a("finsky.main_cache_size_mb", localInteger1);
    Integer localInteger2 = Integer.valueOf(4);
    et = a.a("finsky.image_cache_size_mb", localInteger2);
    Integer localInteger9 = Integer.valueOf(1);
    fe = a.a("finsky.cache_and_sync.main_cache_prefetch_increase_mb", localInteger9);
    Integer localInteger3 = Integer.valueOf(5);
    eu = a.a("finsky.cache_and_sync.image_prefetch_cache_size_mb", localInteger3);
    Boolean localBoolean2 = Boolean.valueOf(false);
    bp = a.a("finsky.debug_options_enabled", localBoolean2);
    bq = a.a("finsky.debug_send_event_to_logcat", localBoolean2);
    br = a.a("finsky.debug_display_stream_info", localBoolean2);
    av = a.a("finsky.cache_and_sync.interactive_sync_enabled", localBoolean2);
    jJ = a.a("finsky.user_check_for_self_update_enabled", localBoolean1);
    bo = a.a("finsky.debug_limited_user_state", localBoolean2);
    dX = a.a("finsky.gtv_navigational_suggestions_enabled", localBoolean2);
    eS = a.a("finsky.extra_menu_item_title", "");
    eT = a.a("finsky.extra_menu_item_url", "");
    a.a("finsky.games_browse_url", "home?c=3&cat=GAME");
    a.a("finsky.dfe_logs_admob_enabled", localBoolean1);
    Integer localInteger4 = Integer.valueOf(15);
    a.a("finsky.logs_dispatch_interval_seconds", localInteger4);
    a.a("finsky.maximum_log_queue_size", Integer.valueOf(40));
    hG = a.a("finsky.redeem_terms_and_conditions_url", "https://play.google.com/intl/%locale%/about/redeem-terms.html");
    jp = a.a("finsky.terms_of_service_url", "https://play.google.com/intl/%locale%/about/play-terms.html");
    hw = a.a("finsky.read_book_url", "https://play.google.com/books/reader");
    aT = a.a("finsky.content_filter_info_url", "http://www.google.com/support/androidmarket/bin/answer.py?answer=1075738");
    fJ = a.a("finsky.music_dmca_report_link", "https://www.google.com/support/artists?p=DMCA");
    eX = a.a("finsky.local_link_resolve.details_url_modern", "https://play.google.com/store/apps/details");
    eW = a.a("finsky.local_link_resolve.details_url_legacy", "https://market.android.com/details");
    eV = a.a("finsky.local_link_resolve.black_listed_params", "inline,goToHome,skipCache");
    gE = a.a("finsky.permission_buckets_learn_more_link", "https://support.google.com/googleplay/?p=app_permissions");
    gl = a.a("finsky.optional_permission_buckets_learn_more_link", "https://support.google.com/googleplay/?p=app_permissons_m");
    dL = a.a("finsky.gaia_opt_out_learn_more_link", "https://support.google.com/googleplay/answer/1626831");
    jn = a.a("finsky.targets_sdk23_whitelist", "");
    dI = a.a("finsky.foreground_coordinator.minimum_api_level", Integer.valueOf(14));
    a.a("finsky.foreground_coordinator.release_max_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    dJ = a.a("finsky.foreground_coordinator.timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(10L)));
    dZ = a.a("finsky.has_fop_cache_timeout_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    ea = a.a("finsky.has_fop_cache_timeout_shorter_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    hp = a.a("finsky.prompt_for_fop_snooze_schedule_m", "10080");
    cK = a.a("finsky.enable_sensitive_logging", localBoolean2);
    cD = a.a("finsky.enable_playlog", localBoolean1);
    cl = a.a("finsky.enable_account_less_logging", localBoolean1);
    dH = a.a("finsky.force_post_purchase_cross_sell", localBoolean2);
    gQ = a.a("finsky.playlog_max_storage_size_bytes", Long.valueOf(at.d.a(2L)));
    gS = a.a("finsky.playlog_recommended_file_size_bytes", Long.valueOf(at.c.a(32L)));
    gO = a.a("finsky.playlog_delay_between_uploads_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    gR = a.a("finsky.playlog_min_delay_between_uploads_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    gN = a.a("finsky.playlog_app_in_foreground_delay_between_uploads_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5L)));
    gT = a.a("finsky.play_logging_server_url", "https://play.googleapis.com/play/log");
    gU = a.a("finsky.play_logging_server_timestamp_url", "https://play.googleapis.com/play/log/timestamp");
    a.a("finsky.headless_play_logging_server_url", "https://www.googleapis.cn/play/log");
    a.a("finsky.headless_play_logging_timestamp_server_url", "https://www.googleapis.cn/play/log/timestamp");
    a.a("finsky.kill_switch_use_headless_play_logging_url", localBoolean2);
    a.a("finsky.kill_switch_headless_whitelisted_logging", localBoolean2);
    gP = a.a("finsky.playlog_impression_settle_time_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2L)));
    a.a("finsky.vending_request_timeout_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(20L)));
    hf = a.a("finsky.playlog_upload_timeout_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(40L)));
    gM = a.a("finsky.playlog_allow_non_existing_log_dirs", localBoolean1);
    ld = a.a("finsky.volley_buffer_pool_size_kb", Integer.valueOf(256));
    hH = a.a("finsky.reduced_billing_address_requires_phonenumber", localBoolean1);
    jK = a.a("vending_address_server_url", "http://i18napis.appspot.com/address");
    jL = a.a("vending_hide_content_rating", localBoolean2);
    jk = a.a("finsky.support_url", "https://support.google.com/googleplay/digital-content/#topic=3364261");
    ed = a.a("finsky.support_enable_background_data_url", "https://support.google.com/googleplay/answer/1663315");
    ce = a.a("finsky.support_edit_payment_method_url", "https://payments.google.com/manage/paymentMethods");
    hh = a.a("finsky.pre_purchase_sharing_enabled", localBoolean1);
    eQ = a.a("finsky.launch_urls_enabled", localBoolean1);
    dd = a.a("finsky.external_referrer_install_organic", "utm_source=google-play&utm_medium=organic");
    fC = a.a("finsky.play_guide_referrer_install_organic", "utm_source=play-guide&utm_medium=organic");
    dc = a.a("finsky.external_referrer_install_deep_link", "utm_source=(not%20set)&utm_medium=(not%20set)");
    de = a.a("finsky.external_referrer_lifespan_ms", Long.valueOf(TimeUnit.DAYS.toMillis(90L)));
    a.a("finsky.subscriptions_enabled", localBoolean1);
    js = a.a("finsky.third_party_app_overlay_whitelist", "");
    jr = a.a("finsky.third_party_app_overlay_aia_whitelist", "");
    cQ = a.a("finsky.enable_third_party_inline_app_installs", localBoolean2);
    cP = a.a("finsky.enable_third_party_direct_purchases", localBoolean2);
    cm = a.a("finsky.enable_android_auto_direct_purchases", localBoolean2);
    bK = a.a("finsky.direct_purchase_api_caller_whitelist_for_apps", "");
    cy = a.a("finsky.enable_inline_app_installs_allow_updates", localBoolean1);
    cN = a.a("finsky.enable_subscription_instrument_update", localBoolean1);
    cS = a.a("finsky.enable_third_party_subscription_instrument_update", localBoolean2);
    cI = a.a("finsky.enable_redeem_intent_api", localBoolean1);
    cR = a.a("finsky.enable_third_party_redeem_intent_api", localBoolean2);
    cO = a.a("finsky.enable_third_party_details_api", localBoolean2);
    cr = a.a("finsky.enable_details_api", localBoolean2);
    bi = a.a("finsky.daily_hygiene_preload_experiments", localBoolean1);
    cT = a.a("finsky.enable_unauthenticated_app_updates", localBoolean2);
    jv = a.a("finsky.unauth_updates_dependencies_whitelist", "com.google.android.gms");
    bl = a.a("finsky.daily_hygiene_schedule_unauthenticated", localBoolean1);
    bc = a.a("finsky.daily_hygiene_foreground_interval_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    bk = a.a("finsky.daily_hygiene_retry_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(10L)));
    bf = a.a("finsky.daily_hygiene_immediate_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    en = a.a("finsky.hygiene_core_phenotype_timeout", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    hM = a.a("finsky.routine_hygiene.hard_no_recent_success_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    hP = a.a("finsky.routine_hygiene.scheduler_window_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    hN = a.a("finsky.routine_hygiene.minimum_delay_after_success_ms", Long.valueOf(TimeUnit.HOURS.toMillis(4L)));
    hO = a.a("finsky.routine_hygiene.double_frequency_scheduler_window_ms", Long.valueOf(TimeUnit.HOURS.toMillis(12L)));
    Object localObject1 = Float.valueOf(0.1F);
    a.a("finsky.daily_hygiene_reschedule_jitter_factor", (Float)localObject1);
    Object localObject4 = Float.valueOf(0.5F);
    a.a("finsky.daily_hygiene_initial_reschedule_jitter_factor", (Float)localObject4);
    bj = a.a("finsky.daily_hygiene_provision_holdoff_max_ms", Long.valueOf(TimeUnit.HOURS.toMillis(23L)));
    be = a.a("finsky.daily_hygiene_holdoff_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    bd = a.a("finsky.daily_hygiene_holdoff_during_self_update", localBoolean2);
    Integer localInteger7 = Integer.valueOf(-1);
    bh = a.a("finsky.daily_hygiene_emergency_version_code_low", localInteger7);
    bg = a.a("finsky.daily_hygiene_emergency_version_code_high", localInteger7);
    aa = a.a("finsky.auto_update_exclude_foreground_services", localBoolean1);
    dQ = a.a("finsky.play_services_auto_update_enabled", localBoolean1);
    dR = a.a("finsky.gms_core_auto_update_projection_holdoff", localBoolean1);
    jm = a.a("finsky.synchronized_gmscore_update_timeout", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    ah = a.a("finsky.auto_update_v2.blacklist", "com.google.android.gms,com.android.chrome,com.google.android.instantapps.supervisor");
    cf = a.a("finsky.edu_device_policy_package_name", "com.google.android.apps.enterprise.dmagent");
    bZ = a.a("finsky.download_manager_parse_download_ids", localBoolean1);
    bT = a.a("finsky.download_bytes_mobile_recommended", Long.valueOf(at.d.a(100L) + at.c.a(25L)));
    bS = a.a("finsky.download_bytes_mobile_maximum", Long.valueOf(Long.MAX_VALUE));
    Long localLong1 = Long.valueOf(-1L);
    bY = a.a("finsky.download_free_space_threshold_bytes", localLong1);
    Integer localInteger5 = Integer.valueOf(100);
    bX = a.a("finsky.download_free_space_apk_size_factor", localInteger5);
    cc = a.a("finsky.download_send_base_version", localBoolean1);
    bw = a.a("finsky.download_deliverydata_expiration", Long.valueOf(TimeUnit.HOURS.toMillis(4L)));
    ca = a.a("finsky.download_patch_free_space_factor", Integer.valueOf(210));
    bU = a.a("finsky.download_external_file_size_min_bytes", Long.valueOf(at.d.a(50L)));
    Integer localInteger10 = Integer.valueOf(200);
    bV = a.a("finsky.download_external_free_space_factor", localInteger10);
    cd = a.a("finsky.downloads_send_request_header_info", localBoolean1);
    bW = a.a("finsky.download_external_free_space_threshold_bytes", Long.valueOf(at.d.a(64L)));
    hl = a.a("finsky.preserve_forward_lock_api_max", Integer.valueOf(19));
    I = a.a("finsky.app_restore_failsafe_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(10L)));
    J = a.a("finsky.app_restore_fetch_list_max_attempts", localInteger2);
    O = a.a("finsky.app_restore_retry_fetch_list_holdoff_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(2L)));
    H = a.a("finsky.app_restore_download_max_attempts", localInteger2);
    N = a.a("finsky.app_restore_retry_download_holdoff_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(4L)));
    M = a.a("finsky.app_restore_retry_download_holdoff_high_priority_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    G = a.a("finsky.app_restore_dependencies_acquire_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    lw = a.a("finsky.app_restore_dependencies_auto_acquire_whitelist", "com.google.android.gms");
    K = a.a("finsky.app_restore_retry_download_blacklist", "198,498");
    a.a("finsky.app_restore_app_icon_max_attempts", localInteger2);
    L = a.a("finsky.app_restore_retry_delay_exponential_base", Float.valueOf(1.5F));
    F = a.a("finsky.app_restore_allow_fresh_installs_in_suw", localBoolean2);
    s = a.a("finsky.android_tv_check_user_setup_complete_2", localBoolean2);
    fA = a.a("finsky.minimum_videos_app_version_code_post_honeycomb", Integer.valueOf(20090));
    fz = a.a("finsky.minimum_music_app_version_code", Integer.valueOf(1409));
    fy = a.a("finsky.minimum_game_app_version_code", Integer.valueOf(50000000));
    gJ = a.a("finsky.platform_anti_malware_enabled", localBoolean1);
    t = a.a("finsky.anti_malware_consent_required", localBoolean1);
    iY = a.a("finsky.show_anti_malware_consent", localBoolean1);
    jI = a.a("finsky.use_tos_as_verify_apps_consent", localBoolean2);
    kB = a.a("finsky.verify_apps_restore_notifications_enabled", localBoolean1);
    Object localObject5 = Integer.valueOf(8400000);
    kn = a.a("finsky.verify_apps_min_gms_version_for_consent_in_secure_settings", (Integer)localObject5);
    kA = a.a("finsky.verify_apps_request_consent_before_setup", localBoolean2);
    ko = a.a("finsky.verify_apps_min_gms_version_for_device_wide_consent", localInteger7);
    kd = a.a("finsky.verify_apps_googler_whitelist_enabled", localBoolean2);
    ke = a.a("finsky.verify_apps_grant_googler_upload_consent", localBoolean1);
    jX = a.a("finsky.verify_apps_check_cache_enabled", localBoolean1);
    kp = a.a("finsky.verify_apps_multi_install_request_throttling_enabled", localBoolean1);
    jP = a.a("finsky.verify_apps_app_blocked_broadcast_component", "");
    gI = a.a("finsky.platform_anti_malware_dialog_delay_ms", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    a.a("finsky.anti_malware_activity_enabled", localBoolean1);
    kV = a.a("finsky.verify_installed_packages_minimum_wait_time_ms", Long.valueOf(TimeUnit.DAYS.toMillis(6L)));
    kU = a.a("finsky.verify_installed_packages_lite_minimum_wait_time_ms", Long.valueOf(TimeUnit.HOURS.toMillis(22L)));
    kT = a.a("finsky.verify_installed_packages_has_pha_wait_ms", Long.valueOf(TimeUnit.HOURS.toMillis(22L)));
    kS = a.a("finsky.verify_installed_packages_has_offline_download_wait_ms", Long.valueOf(TimeUnit.HOURS.toMillis(22L)));
    a.a("finsky.verify_apps_cached_verdict_timeout_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    a.a("finsky.verify_apps_removed_package_timeout_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    kq = a.a("finsky.verify_apps_multi_install_request_initial_backoff_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    kr = a.a("finsky.verify_apps_multiple_install_requests_max_timeout_ms", Long.valueOf(TimeUnit.HOURS.toMillis(24L)));
    kX = a.a("finsky.verify_installed_packages_timeout_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(15L)));
    Integer localInteger6 = Integer.valueOf(8);
    kW = a.a("finsky.verify_installed_packages_retries", localInteger6);
    Object localObject2 = Float.valueOf(2.0F);
    kQ = a.a("finsky.verify_installed_packages_backoff_multiplier", (Float)localObject2);
    kI = a.a("finsky.verify_apps_timeout_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(3L)));
    kt = a.a("finsky.verify_apps_retries", localInteger1);
    Object localObject3 = Float.valueOf(1.0F);
    jV = a.a("finsky.verify_apps_backoff_multiplier", (Float)localObject3);
    kN = a.a("finsky.verify_apps_user_decision_timeout_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(15L)));
    kM = a.a("finsky.verify_apps_user_decision_retries", localInteger6);
    kL = a.a("finsky.verify_apps_user_decision_backoff_multiplier", (Float)localObject2);
    kR = a.a("finsky.verify_installed_packages_enabled", localBoolean1);
    kY = a.a("finsky.verify_installed_play_packages_enabled", localBoolean1);
    lb = a.a("finsky.verify_system_packages_probability", (Float)localObject1);
    la = a.a("finsky.verify_system_has_pha_packages_probability", (Float)localObject3);
    a.a("finsky.verify_apps_minimum_gms_core_version_code_for_shared_id", Integer.valueOf(7600000));
    ki = a.a("finsky.verify_apps_log_to_clearcut", localBoolean2);
    kh = a.a("finsky.verify_apps_log_snet_id_in_verification_errors", localBoolean2);
    kj = a.a("finsky.verify_apps_log_user_decision_to_csd_server", localBoolean1);
    km = a.a("finsky.verify_apps_installer_digest_count", localInteger1);
    cz = a.a("finsky.enable_lite_verify_installed_packages", localBoolean1);
    gg = a.a("finsky.offline_verify_app_enabled", localBoolean2);
    ku = a.a("finsky.verify_apps_offline_malware_timeout_seconds", Long.valueOf(10L));
    gf = a.a("finsky.offline_autoscan_unconsented_devices_enabled", localBoolean2);
    gd = a.a("finsky.offline_autoscan_enabled", localBoolean2);
    ge = a.a("finsky.offline_autoscan_logging_enabled", localBoolean2);
    jx = a.a("finsky.offline_autoscan_notification_wait_ms", Long.valueOf(TimeUnit.DAYS.toMillis(180L)));
    kw = a.a("finsky.verify_apps_pha_learn_more_url", "https://support.google.com/android/answer/2812853");
    ks = a.a("finsky.verify_apps_muws_learn_more_url", "https://support.google.com/android/answer/2812853");
    kO = a.a("finksy.verify_apps_vole_endpoint", "voledevice-pa.googleapis.com");
    kb = a.a("finksy.verify_apps_enable_vole_v3", localBoolean2);
    bH = a.a("finsky.device_wide_unknown_source_block_v4", localBoolean2);
    Integer localInteger8 = Integer.valueOf(2);
    am = a.a("finsky.bind_device_wide_unknown_source_block_timeout", localInteger8);
    bG = a.a("finsky.device_wide_unknown_source_block_broadcast_timeout", localInteger9);
    bF = a.a("finsky.device_wide_non_work_profile_phas_enabled", localBoolean2);
    dY = a.a("harmful_across_profiles_list", "trojan,backdoor,hostile_downloader,rooting");
    fB = a.a("mobile_unwanted_software_threat_types", "data_collection,uncommon,impersonation,suspicious");
    k = a.a("finsky.cache_and_sync.is_allowed", localBoolean1);
    kP = a.a("finsky.verify_apps_xlb_warmup_time_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    kG = a.a("finsky.verify_apps_threat_type_cache_timeout_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    ka = a.a("finsky.verify_apps_enable_list_harmful_apps_api", localBoolean2);
    kz = a.a("finsky.verify_apps_report_autoscan_lite_scan_time", localBoolean2);
    kf = a.a("finsky.verify_apps_hostname", "safebrowsing.google.com");
    kH = a.a("finsky.verify_apps_timeout_logging_enabled", localBoolean2);
    kC = a.a("finsky.verify_apps_silently_block_enabled", localBoolean1);
    jR = a.a("finsky.verify_apps_auto_disable_enabled_v1", localBoolean1);
    jQ = a.a("finsky.verify_apps_auto_disable_allow_re_enable_v1", localBoolean1);
    jT = a.a("finsky.verify_apps_auto_disable_re_enable_false_positives_v1", localBoolean1);
    jS = a.a("finsky.verify_apps_auto_disable_log_errors_v1", localBoolean1);
    bm = a.a("finsky.days_to_wait_before_auto_disable_system_pha_ms", Long.valueOf(TimeUnit.DAYS.toMillis(6L)));
    kg = a.a("finsky.verify_apps_implicit_suppress_warning", localBoolean1);
    jN = a.a("finsky.verify_apps_amputation_enabled", localBoolean2);
    jM = a.a("finsky.verify_apps_amputation_allow_re_enable", localBoolean2);
    jO = a.a("finsky.verify_apps_amputation_log_errors", localBoolean2);
    kK = a.a("finsky.verify_apps_upload_managed_device_info", localBoolean1);
    kv = a.a("finsky.verify_apps_offline_managed_device_policy_enabled", localBoolean1);
    jU = a.a("finsky.verify_apps_autoscan_upload_installer_info", localBoolean1);
    jW = a.a("finsky.verify_apps_broadcast_pha_event", localBoolean2);
    kJ = a.a("finsky.verify_apps_tv_notification_enabled", localBoolean2);
    kx = a.a("finsky.verify_apps_play_install_stale_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    jY = a.a("finsk.verify_apps_cleanup_play_install_age_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    kc = a.a("finsky.verify_apps_full_scan_after_unverified_enabled", localBoolean2);
    localObject1 = Integer.valueOf(10);
    jZ = a.a("finsky.verify_apps_datastore_audit_stack_depth", (Integer)localObject1);
    kE = a.a("finsky.verify_apps_sim_hash_limit", localInteger3);
    kF = a.a("finsky.verify_apps_sim_hash_min_strings", Integer.valueOf(128));
    kD = a.a("finsky.verify_apps_sim_hash_error_limit", localInteger1);
    ky = a.a("finsky.verify_apps_recompute_apk_percent", Float.valueOf(0.03F));
    kl = a.a("finsky.verify_apps_device_status_retries", localInteger9);
    bA = a.a("device_country", "");
    cJ = a.a("finsky.enable_review_comments", localBoolean1);
    a.a("finsky.enable_remove_apps_from_library", localBoolean1);
    eq = a.a("finsky.iabv3_max_purchases_in_response", localInteger5);
    er = a.a("finsky.iabv3_network_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(20L)));
    localObject2 = Integer.valueOf(20);
    es = a.a("finsky.iabv3_sku_details_max_size", (Integer)localObject2);
    eo = a.a("finsky.iabv3_first_party_api_enabled", localBoolean1);
    ep = a.a("finsky.iabv3_first_party_api_unrestricted_access", localBoolean2);
    localObject3 = Long.valueOf(1000L);
    ar = a.a("finsky.bulk_acquire_short_delay", (Long)localObject3);
    ap = a.a("finsky.bulk_acquire_long_delay", Long.valueOf(2000L));
    aq = a.a("finsky.bulk_acquire_prepare_max_threads", localInteger8);
    a.a("finsky.places_api_bias_radius_meters", Integer.valueOf(50000));
    lx = a.a("finsky.whitelisted_places_api_countries", "0:CA,CH,US");
    gH = a.a("finsky.places_api_key", "AIzaSyCsc46SHdb57jPJa9fo7euV_HBDgwdrXsE");
    X = a.a("finsky.authentication_continue_url", "https://play.google.com");
    aX = a.a("finsky.project_space_laser", "");
    gw = a.a("finsky.password_recovery_url", "https://accounts.google.com/RecoverAccount?fpOnly=1&Email=%email%");
    gv = a.a("finsky.password_max_failed_attempts", localInteger3);
    cL = a.a("finsky.enable_session_stats_log", localBoolean1);
    cU = a.a("finsky.enable_upload_device_config", localBoolean1);
    bs = a.a("finsky.default_hygiene_job_count_down_latch_timeout", Long.valueOf(TimeUnit.MINUTES.toSeconds(5L) / 2L));
    fG = a.a("finsky.music_app_subscription_backend_docid_blacklist", "Saeaaaaaa");
    fF = a.a("finsky.all_access_backend_docid", "Saeaaaaaa");
    dg = a.a("finsky.family_music_plan_backend_docid", "Sfamilymusicaccess");
    fH = a.a("finsky.music_app_subscription_resignup_enabled", localBoolean2);
    g = a.a("finsky.additional_targets", null);
    hC = a.a("finsky.recently_updated_window_size_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    gm = a.a("finsky.outstanding_notification_time_delay_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    fX = a.a("finsky.notification_assist.historical_interactions_ttl_ms", Long.valueOf(TimeUnit.DAYS.toMillis(60L)));
    fY = a.a("finsky.notification_assist.max_delay_ms", Long.valueOf(TimeUnit.HOURS.toMillis(12L)));
    fW = a.a("finsky.notification_assist.delay_step_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(30L)));
    fZ = a.a("finsky.notification_assist.static_delay_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    a.a("finsky.auto_update_broadcast_debouncer_delay", Long.valueOf(TimeUnit.SECONDS.toMillis(3L)));
    a.a("finsky.auto_update_broadcast_stabilizer_delay", Long.valueOf(TimeUnit.MINUTES.toMillis(3L)));
    a.a("finsky.auto_update_throttle_interval", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    ag = a.a("finsky.auto_update_skip_power_check_interval", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    ai = a.a("finsky.auto_update_wifi_check_interval", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    ab = a.a("finsky.auto_update_gearhead_check_interval", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    a.a("finsky.auto_update_drivestate_check_interval", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    ad = a.a("finsky.auto_update_job_scheduler_gearhead_delay", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    ae = a.a("finsky.auto_update_job_scheduler_timeout_ms", Long.valueOf(TimeUnit.HOURS.toMillis(23L)));
    af = a.a("finsky.auto_update_job_scheduler_min_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(2L)));
    Z = a.a("finsky.auto_update_disabled_packages", localBoolean1);
    ao = a.a("finsky.browse_data_sync.window_start_delay_s", Long.valueOf(TimeUnit.MINUTES.toSeconds(2L)));
    jE = a.a("finsky.upload_dynamic_config.window_start_delay_s", Long.valueOf(TimeUnit.MINUTES.toSeconds(2L)));
    an = a.a("finsky.browse_data_sync.window_end_delay_s", Long.valueOf(TimeUnit.HOURS.toSeconds(23L)));
    jt = a.a("finsky.upload_dynamic_config.window_end_delay_s", Long.valueOf(TimeUnit.HOURS.toSeconds(23L)));
    ay = a.a("finsky.cache_and_sync.scheduling_interval_millis", Long.valueOf(TimeUnit.HOURS.toMillis(23L)));
    dk = a.a("finsky.cache_and_sync.battery_percentage_threshold", (Integer)localObject2);
    dl = a.a("finsky.cache_and_sync.fetch_suggestions_check_interval_millis", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    as = a.a("finsky.cache_and_sync.complete_sync_interval_millis", Long.valueOf(TimeUnit.HOURS.toMillis(24L)));
    by = a.a("finsky.cache_and_sync.dequeue_suggestions_period_s", Long.valueOf(TimeUnit.MINUTES.toSeconds(30L)));
    bx = a.a("finsky.cache_and_sync.dequeue_suggestions_flex_s", Long.valueOf(TimeUnit.MINUTES.toSeconds(5L)));
    az = a.a("finsky.cache_and_sync.scheduling_long_period_seconds", Long.valueOf(TimeUnit.DAYS.toSeconds(7L)));
    aA = a.a("finsky.cache_and_sync.scheduling_short_period_seconds", Long.valueOf(TimeUnit.HOURS.toSeconds(24L)));
    ax = a.a("finsky.cache_and_sync.scheduling_enable_long_period", localBoolean2);
    aB = a.a("finsky.cache_and_sync.scheduling_window_end_s", Long.valueOf(TimeUnit.HOURS.toSeconds(1L)));
    au = a.a("finsky.cache_and_sync.images_soft_ttl_days_millis", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    at = a.a("finsky.cache_and_sync.images_hard_ttl_days_millis", Long.valueOf(TimeUnit.DAYS.toMillis(30L)));
    aw = a.a("finsky.cache_and_sync.max_num_of_entries_to_sync", Integer.valueOf(500));
    lc = a.a("finsky.video_app_trailer_playback_min_version", Integer.valueOf(27030));
    dt = a.a("finsky.newsstand_app_first_version", Integer.valueOf(132340703));
    fS = a.a("finsky.newsstand_free_subscription_completion_version", Integer.valueOf(2015020408));
    dN = a.a("finsky.gel_package_name", "com.google.android.googlequicksearchbox");
    eU = a.a("finsky.library_replicator_reschedule_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    hg = a.a("finsky.positive_rate_threshold", localInteger1);
    iP = a.a("finsky.setupWizardRestoreHeaderBlueGraphicUrl", "https://lh3.ggpht.com/1ekRt1ToFJPlPrDmTUbaWcD8HtQxQk_KEp8l8-FZXbRnzdQaR-rrzn3xo250k9S1epc");
    iQ = a.a("finsky.setupWizardRestoreWideHeaderBlueGraphicUrl", "https://lh3.ggpht.com/0CsFZStY7DZrq_SXIMl8wcPSgvs3OESY6m30Ae8MrQnX5UnwWqo6hMTClDAgrWUzA7n_YQ");
    iL = a.a("finsky.setupWizardRestoreFinalHoldBlueHeaderUrl", "https://lh3.ggpht.com/SvoAUkpx064vMnO5VnDaXJYNYGojPIsijFUq0enaXckHjvSMHNnSP85oVlRTRMZzGte7");
    iM = a.a("finsky.setupWizardRestoreFinalHoldHeaderBlueLandscapeUrl", "https://lh3.ggpht.com/mq8qQcSnAeXJTpM52HHnnD79s4bEshlT3vKbS5uNl9Lie_TwtfhhFXrJ7XTCG_FptaTN");
    iK = a.a("finsky.setupWizardRestoreFinalHoldBlueHeaderTabletUrl", "https://lh3.ggpht.com/aARRX4T1er_Y3-Q3O9IOI-UyVo-otrCq8wkeNvQiD4k-v_b3OJonycdeK-ttWool3I4");
    iO = a.a("finsky.setup_wizard_restore_final_hold_short_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    iN = a.a("finsky.setup_wizard_restore_final_hold_long_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(3L)));
    iC = a.a("finsky.setup_wizard_additional_account_vpa_enable", localBoolean1);
    iI = a.a("finsky.setupWizardPaymentHeaderBlueGraphicUrl", "https://lh3.ggpht.com/5FYtYy0wEOSW0FXswusE7s2_gicFCwm1ngI-7odbhsNCkTGI5S6Jk6FWtGOjkPgmPhXIkw");
    iJ = a.a("finsky.setupWizardPaymentHeaderWideBlueGraphicUrl", "https://lh3.ggpht.com/WqCZKwL-R3IQhxcyzDEYPKLEwTjc_UV42J4okAm3dEVKm0ktJb7kFcfaJA7DBU9pPNMw");
    iH = a.a("finsky.setupWizardForceResizeForKeyboardInFullscreen", localBoolean1);
    fE = a.a("finsky.music_all_access_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=album_detail_page&utm_campaign=30daytrial");
    a.a("finsky.music_all_access_artist_banner_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=banner&utm_campaign=artistpage&coupontype=vanity&coupon=SEARCH60B");
    a.a("finsky.music_all_access_album_banner_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=banner&utm_campaign=albumpage&coupontype=vanity&coupon=APPS60B");
    a.a("finsky.music_all_access_artist_button_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=card&utm_campaign=artistpage&coupontype=vanity&coupon=SEARCH60A");
    a.a("finsky.music_all_access_album_button_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=card&utm_campaign=albumpage&coupontype=vanity&coupon=APPS60A");
    fD = a.a("finsky.music_all_access_album_artist_control_sign_up_intent_url", "http://play.google.com/music/listen?signup=1&utm_source=playstore&utm_medium=control&utm_campaign=albumpage&coupontype=vanity&coupon=APPS60C");
    fI = a.a("finsky.music_artist_radio_intent_url", "https://play.google.com/music/r/m/%artistId%?play=1&welcome=0&utm_source=playstore&utm_campaign=artist_play_button");
    iG = a.a("finsky.setup_wizard_early_update_enable", localBoolean1);
    iF = a.a("finsky.setup_wizard_early_update_deadlock_max_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5L)));
    iD = a.a("finsky.setup_wizard_early_update_attempts_critical", localInteger1);
    iE = a.a("finsky.setup_wizard_early_update_attempts_regular", localInteger9);
    jC = a.a("finsky.unsubmitted_reviews_max_lifespan_ms", Long.valueOf(TimeUnit.DAYS.toMillis(30L)));
    jl = a.a("finsky.supported_account_types", "com.google.work");
    dM = a.a("finsky.gearhead.external_hosting_lockout", localBoolean1);
    a.a("finsky.wear.node_keep_time_ms", Long.valueOf(TimeUnit.DAYS.toMillis(30L)));
    lq = a.a("finsky.wear.daily_hygiene_enable", localBoolean1);
    lv = a.a("finsky.wear.self_update_enabled", localBoolean2);
    lr = a.a("finsky.wear.gms_update_enabled", localBoolean1);
    lj = a.a("finsky.wear.active_node_time", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    lo = a.a("finsky.wear.auto_update_whitelist", "com.google.android.wearable.app,com.vinodkrishnan.testapp");
    lk = a.a("finsky.wear.auto_install_enable", localBoolean1);
    ln = a.a("finsky.wear.auto_uninstall_enable", localBoolean1);
    lm = a.a("finsky.wear.auto_install_uninstall_whitelist", "com.vinodkrishnan.testapp,com.facebook.orca,com.google.android.googlequicksearchbox");
    ll = a.a("finsky.wear.auto_install_uninstall_blockedlist", "com.google.android.apps.enterprise.dmagent,com.google.android.inputmethod.japanese,com.google.android.inputmethod.korean,com.google.android.marvin.talkback");
    ls = a.a("finsky.wear.gms_version_dependency_enabled", localBoolean1);
    lp = a.a("finsky.wear.boot_hygiene_wait_period", Long.valueOf(TimeUnit.MINUTES.toMillis(15L)));
    lu = a.a("finsky.wear.max_hygiene_retry_count", localInteger8);
    lt = a.a("finsky.wear.hygiene_retry_interval", Long.valueOf(TimeUnit.MINUTES.toMillis(10L)));
    lf = a.a("finsky.wear.hygiene_job_scheduler_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(60L)));
    a.a("finsky.direct_to_backend_intent", localBoolean1);
    cB = a.a("finsky.enable_ok_http", localBoolean1);
    cC = a.a("finsky.enable_ok_http_tls_1_2_on_JB_plus", localBoolean1);
    cp = a.a("finsky.enable_cronet", localBoolean1);
    m = a.a("finsky.allow_force_loading_cronet_only_for_testing", localBoolean2);
    fQ = a.a("finsky.native_libs_supported_abis", "armeabi-v7a");
    fR = a.a("finsky.native_libs_unsupported_abis", "x86,x86_64,mips,mips64");
    hj = a.a("finsky.preregistration_expire_after_acknowledge_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    hk = a.a("finsky.preregistration_force_list", "");
    bN = a.a("finsky.disable_sidewinder_selfupdate", localBoolean1);
    hz = a.a("finsky.reauth_api_get_settings_end_point", "https://www.googleapis.com/reauth/v1beta/users/me/settings");
    hA = a.a("finsky.reauth_api_get_recovery_options_end_point", "https://www.googleapis.com/reauth/v1beta/users/me/recoveryOptionsRapt");
    hB = a.a("finsky.reauth_api_verify_credentials_end_point_with_delegation", "https://www.googleapis.com/reauth/v1beta/users/%user_id%/reauthProofTokens");
    hy = a.a("finsky.reauth_api_auth_token_type", "oauth2:https://www.googleapis.com/auth/accounts.reauth");
    hx = a.a("finsky.reauth_api_account_manager_key", "com.google.android.gms.auth.confirm.CredentialsState");
    hs = a.a("finsky.rapid_auto_update_listing_v2", "");
    hu = a.a("finsky.rapid_auto_update_tos_min_version", localInteger3);
    ht = a.a("finsky.rapid_auto_update_priority", localInteger9);
    hv = a.a("finsky.rapid_unauth_auto_update_any_network", localBoolean1);
    dj = a.a("finsky.feedback_Package_Minimum_Version", Integer.valueOf(4132000));
    di = a.a("finsky.feedback_package", "com.google.android.gms");
    eR = a.a("finsky.legacy_feedback_package", "com.google.android.feedback");
    df = a.a("finsky.family_management_package", "com.google.android.gms");
    fu = a.a("finsky.min_gmscore_version_for_family", (Integer)localObject5);
    fv = a.a("finsky.min_gmscore_version_for_family_v2", Integer.valueOf(9000000));
    fi = a.a("finsky.max_family_music_upgrade_prompt_shown_count", localInteger8);
    iv = a.a("finsky.search_suggest_throttle_interval_ms", Integer.valueOf(150));
    a.a("finsky.package_restore_notifications_kill_switch", localBoolean2);
    gn = a.a("finsky.package_restore_notifications_kill_switch_v2", localBoolean2);
    a.a("finsky.help_url_for_crashing_issues", "https://support.google.com/googleplay/?p=fix_crashing&hl=%lang%");
    ef = a.a("finsky.help_url_for_download_issues", "https://support.google.com/googleplay/?p=fix_download_install&hl=%lang%");
    ee = a.a("finsky.help_url_for_connection_issues", "https://support.google.com/googleplay/?p=fix_connectivity&hl=%lang%");
    ei = a.a("finsky.help_url_for_storage_issues", "https://support.google.com/googleplay/?p=fix_storage&hl=%lang%");
    eh = a.a("finsky.help_url_for_general_issues", "https://support.google.com/googleplay/?p=fix_general&hl=%lang%");
    eg = a.a("finsky.help_url_for_external_storage_missing", "https://support.google.com/android-one/answer/6088895?hl=%lang%");
    a.a("finsky.help_url_for_recovery_options", "https://support.google.com/accounts/answer/1187657?hl=%lang%");
    bJ = a.a("finsky.dfe_managed_context_detection_enabled", localBoolean1);
    bB = a.a("finsky.device_management_helper_enabled", localBoolean1);
    bM = a.a("finsky.disable_non_auth_device_management_helper", localBoolean2);
    d = a.a("finsky.adid_min_gms_core_version", Integer.valueOf(7000000));
    c = a.a("finsky.adid_max_cache_time_ms", Long.valueOf(TimeUnit.HOURS.toMillis(23L)));
    e = a.a("finsky.ad_vtc_duration_threshold_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    f = a.a("finsky.ad_vtc_visible_fraction_threshold", (Float)localObject4);
    dO = a.a("finsky.gift_message_max_character_count", localInteger10);
    localObject4 = Integer.valueOf(50);
    dP = a.a("finsky.gifter_name_max_character_count", (Integer)localObject4);
    a.a("finsky.gifting_with_share_intent_for_first_party", localBoolean2);
    dA = a.a("finsky.flush_logs_no_user_activity_timeout", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    dC = a.a("finsky.flush_logs_on_app_exit_timeout", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    dB = a.a("finsky.flush_logs_on_app_exit_self_update_timeout", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    dE = a.a("finsky.flush_logs_wait_timeout", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    dD = a.a("finsky.flush_logs_schedule_expired_timeout", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    gG = a.a("finsky.phenotype_update_wait_timeout", Long.valueOf(TimeUnit.MINUTES.toMillis(3L)));
    aY = a.a("finsky.crash_file_expired_timeout", Long.valueOf(TimeUnit.HOURS.toMillis(60L)));
    fh = a.a("finsky.max_crash_count", (Integer)localObject2);
    fo = a.a("finsky.min_crash_count_purge_cache", localInteger9);
    fp = a.a("finsky.min_crash_count_purge_intermediate_data", localInteger1);
    ft = a.a("finsky.min_crash_count_purge_user_prefs", localInteger7);
    fs = a.a("finsky.min_crash_count_purge_sticky_tab_data", localInteger8);
    fr = a.a("finsky.min_crash_count_purge_self_update_data", localInteger8);
    fq = a.a("finsky.min_crash_count_purge_job_store_data", localInteger1);
    D = a.a("finsky.app_in_bg_duration_for_updating_experiments_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(30L)));
    C = a.a("finsky.app_in_bg_check_poll_interval_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(10L)));
    bb = a.a("finsky.critical_tasks_running_poll_interval_ms", Integer.valueOf((int)TimeUnit.SECONDS.toMillis(10L)));
    bt = a.a("finsky.defer_process_kill_for_experiments_update_if_device_in_use", localBoolean1);
    gc = a.a("finsky.oauth2_enabled", localBoolean1);
    gK = a.a("finsky.auth_token_type", "androidmarket");
    gL = a.a("finsky.auth_token_type_oauth2", "oauth2:https://www.googleapis.com/auth/googleplay");
    em = a.a("finksy.high_quality_bucket_latency_ms", Integer.valueOf(0));
    localInteger9 = Integer.valueOf(750);
    jh = a.a("finsky.standard_quality_bucket_latency_ms", localInteger9);
    fb = a.a("finsky.low_quality_bucket_latency_ms", Integer.valueOf(1500));
    ej = a.a("finsky.herrevad_reporting_enabled", localBoolean1);
    ly = a.a("finsky.zapp.client.controller", "+com.google.android.gms");
    jf = a.a("finsky.splitinstallservice.maxreadytocomplete", Integer.valueOf(Integer.MAX_VALUE));
    lz = a.a("finsky.zapp.rate_limit_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    jg = a.a("finsky.splitinstallservice.rate_limit_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    je = a.a("finsky.splitinstallservice.gc_timeout_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    jd = a.a("finsky.splitinstallservice.autocompletion_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(60L)));
    gr = a.a("finsky.pai.unauth_acquire_max_attempts", (Integer)localObject1);
    iB = a.a("finsky.send_mvno_related_device_attributes", localBoolean2);
    jD = a.a("finsky.upload_apn_device_attribute", localBoolean1);
    fm = a.a("finsky.max_recent_search_suggestions", localInteger8);
    hR = a.a("finsky.safe_mode.is_enabled", localBoolean2);
    ju = a.a("finsky.unauth_safe_mode.is_enabled", localBoolean2);
    hS = a.a("finsky.safe_mode.timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    hE = a.a("finsky.recovery_mode.immediate_install_enabled", localBoolean1);
    hD = a.a("finsky.recovery_mode.event_logging_enabled", localBoolean2);
    hF = a.a("finsky.recovery_mode.recovered_state_logging_enabled", localBoolean2);
    hQ = a.a("finsky.safe_mode.crash_count", localInteger3);
    cg = a.a("finsky.emergency_self_update.is_enabled", localBoolean2);
    ck = a.a("finsky.emergency_self_update.target_versions", "");
    cj = a.a("finsky.emergency_self_update.escape_pod_url", "");
    ci = a.a("finsky.emergency_self_update.escape_pod_size", Long.valueOf(0L));
    ch = a.a("finsky.emergency_self_update.escape_pod_sha256", "");
    Object localObject6 = Integer.valueOf(300);
    bu = a.a("finsky.delay_before_launching_google_help_ms", (Integer)localObject6);
    iz = a.a("finsky.self_update_v2.enabled", localBoolean1);
    iy = a.a("finsky.self_update_v2.brotli_filebyfile.enabled", localBoolean1);
    jG = a.a("finsky.use_app_lifecycle_to_check_app_in_background_kill_switch.enabled", localBoolean2);
    localInteger10 = Integer.valueOf(5000);
    jA = a.a("finsky.uninstall_manager_backup_timeout_ms", localInteger10);
    Long localLong2 = Long.valueOf(200L);
    jB = a.a("finsky.uninstall_manager_ondatachanged_rebindviews_delay_millis", localLong2);
    localObject5 = Long.valueOf(5000L);
    jz = a.a("finsky.uninstall_manager_app_data_cache_load_timeout_millis", (Long)localObject5);
    gt = a.a("finsky.partner_setup_v2.install_tracking_enabled", localBoolean2);
    gu = a.a("finsky.partner_setup_v2.uri", "content://com.google.android.partnersetup.rlzappprovider/app_installs/new");
    E = a.a("finsky.app_lifecycle.no_user_activity_timeout", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    db = a.a("finsky.event_id_generator.max_event_id", Long.valueOf(1000000000L));
    da = a.a("finsky.event_id_generator.event_id_pool_size", (Long)localObject3);
    go = a.a("finsky.package_update_service.whitelist", "com.google.android.gms");
    cx = a.a("finsky.cronet.enable_http2", localBoolean1);
    cH = a.a("finsky.cronet.enable_quic", localBoolean1);
    iU = a.a("finsky.cronet.should_store_quic_server_configs", localBoolean1);
    fl = a.a("finsky.cronet.max_quic_server_configs_to_store", (Integer)localObject2);
    cG = a.a("finsky.cronet.enable_quic_idle_connection_timeout", localBoolean1);
    fk = a.a("finsky.cronet.max_quic_idle_connection_timeout_seconds", (Integer)localObject6);
    iS = a.a("finsky.cronet.should_migrate_quic_sessions_on_network_change", localBoolean1);
    cF = a.a("finsky.cronet.enable_quic_connection_options", localBoolean1);
    hq = a.a("finsky.cronet.quic_connection_options_setting", "TLPR");
    hr = a.a("finsky.cronet.race_cert_verification", localBoolean1);
    cM = a.a("finsky.cronet.enable_stale_dns", localBoolean1);
    cu = a.a("finsky.enable_dns_cache_warmup", localBoolean1);
    cn = a.a("finsky.enable_brotli", localBoolean1);
    jq = a.a("finsky.testing_program_learn_more_url", "https://support.google.com/googleplay/?p=beta_testing");
    b = a.a("finsky.accidental_purchases_help", "https://support.google.com/googleplay/answer/1626831?hl=%lang%");
    iT = a.a("finsky.should_restore_preview_apps", localBoolean2);
    a.a("finsky.show_wait_for_wifi_legal_toast", localBoolean1);
    localObject6 = Long.valueOf(500L);
    R = a.a("finsky.faster_updates.app_acqusition_delay_ms", (Long)localObject6);
    eM = a.a("finsky.isotope.install_broadcast_action", "com.google.android.instantapps.experiments.FIRST_SYNC");
    eO = a.a("finsky.isotope.install_receiver_class", "com.google.android.instantapps.supervisor.SyncFlagsWakefulReceiver");
    eL = a.a("instantapps:enable_supervisor", localBoolean2);
    dF = a.a("finsky.force_extra_aia_setup", localBoolean2);
    ew = a.a("finsky.install_api.enabled", localBoolean2);
    eN = a.a("finsky.install_api.isotope_install_policy_enabled", localBoolean1);
    T = a.a("finsky.install_api.arc_install_policy_enabled", localBoolean1);
    aC = a.a("finsky.calculate_stable_layout.enabled", localBoolean1);
    gs = a.a("finsky.cache_key.params_prefixes_to_ignore_csv", "nocache_");
    eJ = a.a("finsky.internal-logging-enabled", localBoolean2);
    aZ = a.a("finsky.max_crash_stack_trace_size", Integer.valueOf(4096));
    gk = a.a("finsky.oncreate_postpone_delay_ms", Integer.valueOf(10000));
    cq = a.a("finsky.default_mode_check_conditions.enabled", localBoolean1);
    eY = a.a("finsky.log_checkin_consistency_token_fetches.enabled", localBoolean2);
    aN = a.a("finsky.chrome_key_rotation_spec", "com.chrome.canary:08wXWKFU633Z_75SlQFnM8loIWE,JLskwF5H4K76aKWKdmF52bYTpgA;com.chrome.dev:JpjAJoxuuouwYOyqJ9rkIJhoOwM,JLskwF5H4K76aKWKdmF52bYTpgA;com.chrome.beta:FTOmmaysligQ8XvOlkqiLmTfEVM,JLskwF5H4K76aKWKdmF52bYTpgA");
    aS = a.a("finsky.cold_start_detection_delay_ms", Integer.valueOf(3000));
    hm = a.a("finsky.primes_jank_samplerate", (Integer)localObject1);
    hn = a.a("finsky.primes_jank_use_timeanimator", localBoolean2);
    B = a.a("finsky.app_freshness_threshold_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    jy = a.a("finsky.unenableable_apps", "com.google.android.webview");
    aM = a.a("finsky.certification_status_help_url", "https://support.google.com/googleplay/?p=uncertified_device");
    a.a("finsky.google_verification_url", "https://www.googleapis.com/androidcheck/v1/attestations/verify?key=");
    le = a.a("finsky.vr_metaworld_background_image_url", "https://lh3.googleusercontent.com/qARyU-lzWR_UkIYGdgtk0JyVNRyVs6vu2ww4psmSC9Hk73IGjnK4kbcAjs28DmyEau4");
    a.a("finsky.dfe.endpoints_with_device_config", "/fdfe/preloads");
    iA = a.a("finsky.dfe.send_additional_headers_unauth_requests", localBoolean2);
    eb = a.a("finsky.headless.os_license_directory", "google_play_updater");
    ec = a.a("finsky.headless.os_license_prefix", "open_source_licenses");
    cw = a.a("finsky.headless.enable_opensource_file_update", localBoolean1);
    cv = a.a("finsky.headless.enable_gms_core_update", localBoolean2);
    dS = a.a("finsky.auto_update.gms_core_wifi_threshold_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    h = a.a("finsky.auto_update.aia_supervisor_wifi_threshold_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    ac = a.a("finsky.auto_update.idle_threshold_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    dq = a.a("finsky.fetch_suggestions.processing_lease_millis", Long.valueOf(TimeUnit.MINUTES.toMillis(2L)));
    do = a.a("finsky.fetch_suggestions.max_entry_age_millis", Long.valueOf(TimeUnit.DAYS.toMillis(5L)));
    dp = a.a("finsky.fetch_suggestions.max_entry_failed_attempts_count", localInteger1);
    dn = a.a("finsky.fetch_suggestions.max_entries_per_bulk_fetch", (Integer)localObject1);
    dm = a.a("finsky.fetch_suggestions.max_dfe_processed_count", Integer.valueOf(600));
    dr = a.a("finsky.fetch_suggestions.service_run_cutoff_millis", Long.valueOf(TimeUnit.MINUTES.toMillis(4L)));
    bP = a.a("finsky.disk_utils_latch_await_multiplier", (Long)localObject6);
    bO = a.a("finsky.disk_utils_latch_await_minimum", Long.valueOf(TimeUnit.SECONDS.toMillis(15L)));
    a.a("finsky.wear.wait_for_wifi_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5L)));
    a.a("finsky.wear.wait_for_wifi_increased_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(7L)));
    a.a("finsky.wear.websky_enable_for_alt_mode", localBoolean2);
    a.a("finsky.wear.continue_purchase_on_phone_enabled", localBoolean2);
    a.a("finsky.wear.ios_add_pay_url", "g.co/AddPay");
    a.a("finsky.wear.ios_add_fop_on_phone_enabled", localBoolean1);
    lg = a.a("finsky.wear.websky_initial_unmetered_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(60L)));
    li = a.a("finsky.wear.websky_unmetered_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    a.a("finsky.wear.wearsky_initial_wifi_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    a.a("finsky.wear.wearsky_wifi_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(3L)));
    lh = a.a("finsky.wear.websky_manual_unmetered_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    a.a("finsky.wear.request_wifi_on_start_for_alt_mode", localBoolean1);
    a.a("finsky.wear.locale_bitmap_loader_cache_size_kb", localInteger7);
    a.a("finsky.wear.create_pin_on_phone_link", "https://accounts.google.com/resetpin");
    a.a("finsky.wear.create_pin_on_phone_link_customized", "https://accounts.google.com/AccountChooser?Email=<EMAIL_FOR_ACCOUNT_CHOOSER>&continue=https%3A%2F%2Faccounts.google.com%2Fresetpin%3Fcontinue%3Dhttps%253A%252F%252Fplay.google.com%252Flanding%252Fwear%252Faccounts%252Fpincreated%252Fpincreated.html");
    a.a("finsky.wear.learn_more_about_auth_link", "https://support.google.com/googleplay/answer/1626831");
    a.a("finsky.wear.cluster_max_size", localInteger8);
    a.a("finsky.wear.splash_screen_spinner_delay_ms", Integer.valueOf(800));
    a.a("finsky.wear.phone_app_state_job_scheduler_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(60L)));
    a.a("finsky.wear.unauth_home_action_drawer_timeout", Long.valueOf(TimeUnit.SECONDS.toMillis(1L)));
    gW = a.a("finsky.pss.en.restorepackages_v1_killswitch", localBoolean2);
    gX = a.a("finsky.pss.whitelist_and_signatures_v1", "com.android.vending:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00;com.google.android.gms:1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00,F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83;com.google.android.apps.pixelmigrate:AFEE62FB653C9D863D1A6D6046B35225BF6380DD4657B105E8331A1DE49F9F91,E52BF33122251A20E747BA9D26AED7A4B4A75692C579171A425F72D6EED5760C;com.google.android.apps.restore:56BE132B780656FE2444CD34326EB5D7AAC91D2096ABF0FE673A99270622EC87,CE74646CCC647C1640C4571023E1CF71B90E4D1D07167C184BE29136449E4C7F;com.google.android.tungsten.setupwraith:84A683A7458CB13FFB3776E9E42B83AF32C569ECDC0B9DDA3CBFECA69E15B622,906034BDC49E2E7DFAE785BEA2AD1816813641C3A47D3AF8E41CC23299ADC30D;com.google.android.setupwizard:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00;org.chromium.arc.applauncher:D78D2C53EEFD3E5A34DAAA1006CCD21C170887FCB76E04CF48414B86504C3C78");
    ha = a.a("finsky.pss.en.restorepackages_v2_killswitch", localBoolean2);
    gY = a.a("finsky.pss.whitelist_and_signatures_v2", "com.android.vending:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00;com.google.android.gms:1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00,F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83;com.google.android.apps.pixelmigrate:AFEE62FB653C9D863D1A6D6046B35225BF6380DD4657B105E8331A1DE49F9F91,E52BF33122251A20E747BA9D26AED7A4B4A75692C579171A425F72D6EED5760C;com.google.android.apps.restore:56BE132B780656FE2444CD34326EB5D7AAC91D2096ABF0FE673A99270622EC87,CE74646CCC647C1640C4571023E1CF71B90E4D1D07167C184BE29136449E4C7F;com.google.android.tungsten.setupwraith:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00;com.google.android.setupwizard:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00;org.chromium.arc.applauncher:D78D2C53EEFD3E5A34DAAA1006CCD21C170887FCB76E04CF48414B86504C3C78,830FC77C05BADE2C6DA9941243F4B23AB493C50B8A6149729EBD5C72FA11ECF4;org.chromium.arc.gms:577117617082BA9730616E23CEB970D7557FDFB32284D75DE07E228230D7627B,FBA8B1BC667CC9789D1F366C29E2A4BAC9A1FE5D93E23C7540E4976C816CEE03;com.google.android.wearable.setupwizard:6365B3F75FB737ACB91C25C6F25C4D6787101760888405AC0633FD0CAE881845,301AA3CB081134501C45F1422ABC66C24224FD5DED5FDC8F17E697176FD866AA;com.google.android.car.setupwizard:a56c33bec53f52990782cf7aac8703c94da94cf995dec3118e4c4fa1a3f6e01a,C8A2E9BCCF597C2FB6DC66BEE293FC13F2FC47EC77BC6B2B0D52C11F51192AB8");
    gZ = a.a("finsky.pss.wl_v2_3p", "com.sec.android.easyMover:34DF0E7A9F1CF1892E45C056B4973CD81CCF148A4050D11AEA4AC5A65F900A42,C8A2E9BCCF597C2FB6DC66BEE293FC13F2FC47EC77BC6B2B0D52C11F51192AB8");
    hc = a.a("finsky.pss.en.pau_v2_killswitch", localBoolean2);
    hb = a.a("finsky.pss.notifications_whitelist", "com.android.vending:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00;com.google.android.gms:1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00,F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83;com.google.android.apps.pixelmigrate:AFEE62FB653C9D863D1A6D6046B35225BF6380DD4657B105E8331A1DE49F9F91,E52BF33122251A20E747BA9D26AED7A4B4A75692C579171A425F72D6EED5760C;com.google.android.apps.restore:56BE132B780656FE2444CD34326EB5D7AAC91D2096ABF0FE673A99270622EC87,CE74646CCC647C1640C4571023E1CF71B90E4D1D07167C184BE29136449E4C7F;com.google.android.setupwizard:F0FD6C5B410F25CB25C3B53346C8972FAE30F8EE7411DF910480AD6B2D60DB83,1975B2F17177BC89A5DFF31F9E64A6CAE281A53DC1D1D59B1D147FE1C82AFA00");
    hd = a.a("finsky.pss.signature_check_exempt_package", "com.google.android.tungsten.setupwraith");
    iZ = a.a("finsky.show_completing_setup_notifiaction_as_is", localBoolean1);
    ja = a.a("finsky.show_setup_complete_notifiaction_as_is", localBoolean1);
    jb = a.a("finsky.show_waiting_for_wifi_notifiaction_as_is", localBoolean1);
    hI = a.a("finsky.restore_event_logging_kill_switch", localBoolean2);
    hJ = a.a("finsky.restore_ignore_network_type_field", localBoolean2);
    hi = a.a("finsky.preloads_fetch_timeout", Long.valueOf(TimeUnit.SECONDS.toMillis(15L)));
    gq = a.a("finsky.pai_disable_deferred_notification", localBoolean2);
    gp = a.a("finsky.pai_deferred_notification_debug_support", localBoolean2);
    Q = a.a("finsky.app_size_stats_cache_thread_count", (Integer)localObject1);
    P = a.a("finsky.app_size_stats_cache_expiration_millis", Long.valueOf(TimeUnit.MINUTES.toMillis(5L)));
    w = a.a("finsky.app_data_usage_stats_cache_thread_count", (Integer)localObject1);
    v = a.a("finsky.app_data_usage_stats_cache_expiration_millis", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    x = a.a("finsky.app_data_usage_stats_interval", Long.valueOf(TimeUnit.DAYS.toMillis(30L)));
    u = a.a("finsky.app_data_usage_display_threshold_bytes", Long.valueOf(at.d.a(1L)));
    cA = a.a("finsky.enable_notification_account_verification", localBoolean1);
    fa = a.a("finsky.http.log_requests_curl", localBoolean2);
    fM = a.a("finsky.my_apps_v2_installed_tab_size_sort_delay_millis", localLong2);
    S = a.a("finsky.app_usage_stats_cache_expiration_millis", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    jj = a.a("finsky.storage_space_ui_helper_expiration_millis", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    fd = a.a("finsky.low_storage_assist_card_threshold_bytes", Long.valueOf(at.b.a(1L)));
    cV = a.a("finsky.enable_webapk_install_policy", localBoolean2);
    eI = a.a("finsky.installer_postpone_regular_restores_during_suw", localBoolean1);
    bQ = a.a("finsky.webapk.do_webapk_install_package_check", localBoolean1);
    bR = a.a("finsky.webapk.do_webapk_install_signing_check", localBoolean1);
    a.a("finsky.webapk.webapk_threshold_bypass_bytes", Long.valueOf(10485760L));
    jH = a.a("finsky.use_main_activity_is_ready_check", localBoolean1);
    cs = a.a("finsky.enable_device_owner_install_policy", localBoolean1);
    bC = a.a("finsky.device_owner_install_policy_allowed_packages", "com.google.android.gms");
    ct = a.a("finsky.enable_device_owner_install_policy_signing_check", localBoolean1);
    cE = a.a("finsky.enable_play_protect_home_activity", localBoolean1);
    gV = a.a("finsky.play_protect_home_activity_fallback_url", "https://www.android.com/play-protect/");
    a.a("finsky.my_apps_v2_security_assist_card_timeout_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    fO = a.a("finsky.my_apps_v2_security_verify_apps_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(20L)));
    fN = a.a("finsky.my_apps_v2_security_verify_apps_min_display_time_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2L)));
    bL = a.a("finsky.disable_download_on_roaming_during_suw", localBoolean2);
    localInteger7 = Integer.valueOf(30);
    gh = a.a("finsky.offpeak.enough_minutes_to_download", localInteger7);
    gj = a.a("finsky.offpeak.reschedule_interval_in_minutes", localInteger7);
    gi = a.a("finsky.offpeak.min_minutes_before_reschedule_notice", Integer.valueOf(720));
    eK = a.a("finsky.is_queued_for_wifi_check_for_pending", localBoolean1);
    dV = a.a("finsky.google_play_refund_policy_url", "https://support.google.com/googleplay?p=details_refundpolicy&ctx=%packageNameOrDocid%");
    dU = a.a("finsky.google_play_2h_apps_games_refund_policy_url", "https://support.google.com/googleplay?p=2h_refunds");
    cb = a.a("finsky.download_pending_silent_update_packages", "com.google.android.instantapps.supervisor,com.google.android.gms");
    a.a("finsky.fop_options_cache_timeout_ms", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    bz = a.a("finsky.details_service_mainthread_timeout_ms", Long.valueOf(600L));
    fw = a.a("finsky.min_gmscore_version_for_verify_apps_settings_activity", Integer.valueOf(10500000));
    fx = a.a("finsky.min_gmscore_version_for_security_cards", Integer.valueOf(11000000));
    aP = a.a("finsky.clear_cache_on_reboot", localBoolean2);
    r = a.a("finsky.always_clear_cache_on_any_process_stable_experiment_change", localBoolean2);
    q = a.a("finsky.always_clear_cache_on_account_change", localBoolean2);
    ev = a.a("finsky.include_sim_operator_in_cache_key", localBoolean1);
    bI = a.a("finsky.dfe_dogfood_base_uri", "https://android.clients.google.com/dogfood/fdfe/");
    l = a.a("finsky.phenotype.allow_custom_impl", localBoolean1);
    o = a.a("finsky.phenotype.allow_unauth_targeting", localBoolean1);
    el = a.a("finsky.heterodyne.sync_url", "https://www.googleapis.com/experimentsandconfigs/v1/getExperimentsAndConfigs");
    ek = a.a("finsky.heterodyne.auth_token_type", "oauth2:https://www.googleapis.com/auth/experimentsandconfigs");
    ho = a.a("finsky.project_fi_spn_whitelist", "Fi Network,nova");
    kZ = a.a("finsky.verify_parent_learn_more_url", "https://support.google.com/googleplay/?p=unverified_update");
    gx = a.a("finsky.peer_app_sharing_api.enabled", localBoolean1);
    gD = a.a("finsky.peer_app_sharing_api.whitelist", "com.google.android.apps.nbu.files:IHr5oTOmMMQkagbHnAmUanCED0cC7luqU/N5G1N7DxQ,GXWy8XF3vIml3/MfnmSmyuKBpT3B0dWbHRR/4cgq+gA:12657099;com.lenovo.anyshare.gps:vRAqlGaYlgeNucZlshu9PXZpH/Zq6XUZo2NMNMOgJUI:12657100;cn.xender:LcUe2xGQXnTnEsEjtCzorW9iNofZEusFHxQRZkbvmrM:12657101;com.test.app.p2papp:4zgXuPGanK8Aq7jDeSZGpgQL/zGZ6riVIASvOds9w2Y;com.android.vending.p2papp:4zgXuPGanK8Aq7jDeSZGpgQL/zGZ6riVIASvOds9w2Y");
    gC = a.a("finsky.peer_app_sharing_api.versionWhitelist", "com.google.android.apps.nbu.files:0;com.lenovo.anyshare.gps:0;cn.xender:0;com.test.app.p2papp:0");
    gA = a.a("finsky.peer_app_sharing_api.package_blacklist", "");
    gz = a.a("finsky.peer_app_sharing_api.min_tos_version", localInteger1);
    gy = a.a("finsky.peer_app_sharing_api.frosting_public_keys", "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEZH2+1+E07dnErAD3L6BbTnaohU0bbXriNlJI7VxJU+LjdSwPyXR5pomARAMoyPkMksLz/gitUPtFuJoPL2ziEw==");
    gB = a.a("finsky.peer_app_sharing_api.startup_package_blacklist", "com.android.vending,com.google.android.gms,com.android.providers.downloads");
    dK = a.a("finsky.frosting_only_update_time_ms", Long.valueOf(TimeUnit.DAYS.toMillis(30L)));
    p = a.a("finsky.allow_sending_ad_id_through_dfe_requests", localBoolean1);
    aE = a.a("finsky.home_page_cards_pre_inflate_size", localInteger4);
    aG = a.a("finsky.home_page_cards_pre_inflate_size", Integer.valueOf(25));
    aF = a.a("finsky.home_page_cards_pre_inflate_size", localInteger5);
    aH = a.a("finsky.card_recycled_view_pool_size", localInteger7);
    aJ = a.a("finsky.card_recycled_view_pool_size_large_screen", (Integer)localObject4);
    aI = a.a("finksy.card_recycled_view_pool_size_chromebook", localInteger5);
    aD = a.a("finsky.card_multi_aspect_ratios_recycled_view_pool_size", localInteger7);
    aR = a.a("finsky.cluster_recycled_view_pool_size_large_screen", (Integer)localObject1);
    dW = a.a("finsky.grid_pack_cluster_recycled_view_pool_size_chromebook", (Integer)localObject2);
    fj = a.a("finsky.max_num_of_view_types_in_view_pool", (Integer)localObject1);
    iw = a.a("finsky.self_update_allocate_aggressive.enabled", localBoolean1);
    a.a("finsky.app_discovery_service_threadpool_size", localInteger6);
    z = a.a("finsky.app_discovery_launcher_caller_verification_enabled", localBoolean1);
    A = a.a("finsky.app_discovery_network_request_delay_ms", Long.valueOf(50L));
    y = a.a("finsky.app_discovery_caller_package_name_whitelist", TextUtils.join(",", new String[] { "com.google.android.apps.nexuslauncher", "com.samsung.android.app.galaxyfinder", "org.chromium.arc.gms" }));
    eG = a.a("finsky.install_reasons_to_consider_usage_stats", "restore,restore_vpa");
    eH = a.a("finsky.install_reasons_to_hide_scheduled_state", "auto_update,rapid_auto_update");
    hT = a.a("finsky.safetynet_rescan_key", "");
    eD = a.a("finsky.install_queue.audit_stack_trace_limit", localInteger3);
    eE = a.a("finsky.install_queue.do_not_check_installed_version", localBoolean1);
    dG = a.a("finsky.install_queue.force_using_scheduler", localBoolean2);
    eF = a.a("finsky.install_queue.setup_constraints_interval_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    hK = a.a("finsky.install_queue.restore_reasons", "restore,restore_vpa");
    jw = a.a("finsky.install_queue.unconditional_overwrite_reasons", "single_install,early_update,bulk_update");
    ig = a.a("finsky.scheduler.gstatic_check_thrashing_threshold_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    ie = a.a("finsky.scheduler.gstatic_check_connect_timeout_ms", localInteger10);
    ib = a.a("finsky.scheduler.device_state_observer_debounce_ms", Long.valueOf(3000L));
    if = a.a("finsky.scheduler.gstatic_check_read_timeout_ms", Integer.valueOf(18000));
    hW = a.a("finsky.scheduler.alarm_engine_max_execution_time", Long.valueOf(TimeUnit.MINUTES.toMillis(10L)));
    ii = a.a("finsky.scheduler.job_executor_max_concurrent_jobs", localInteger2);
    ic = a.a("finsky.scheduler.fallback_alarm_manager_one_delay_ms", Long.valueOf(TimeUnit.HOURS.toMillis(12L)));
    id = a.a("finsky.scheduler.fallback_alarm_manager_two_delay_ms", Long.valueOf(TimeUnit.HOURS.toMillis(18L)));
    in = a.a("finsky.scheduler.audit_stack_trace_limit", localInteger1);
    ir = a.a("finsky.scheduler.max_latency", Long.valueOf(TimeUnit.DAYS.toMillis(7L)));
    ih = a.a("finsky.scheduler.job_details_change_response_delay_ms", (Long)localObject5);
    hZ = a.a("finsky.scheduler.clock_set_back_min_latency", Long.valueOf(TimeUnit.HOURS.toMillis(6L)));
    io = a.a("finsky.scheduler.black_listed_job_primary_keys_2", "");
    ij = a.a("finsky.scheduler.job_scheudler_minimum_latency_allowed", (Long)localObject3);
    im = a.a("finsky.scheduler.job_scheduler_wakeup_throttle_ms", Long.valueOf(30000L));
    hY = a.a("finsky.scheduler.alarm_manager_wakeup_throttle_ms", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    localInteger4 = Integer.valueOf(21);
    is = a.a("finsky.scheduler.min_sdk_to_use_job_scheduler", localInteger4);
    iu = a.a("finsky.scheduler.reschedule_cap_ms", Long.valueOf(TimeUnit.HOURS.toMillis(5L)));
    ip = a.a("finsky.scheduler.logging_period_ms", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    ia = a.a("finsky.scheduler.custom_constraint_timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    il = a.a("finsky.scheduler.job_scheduler_timeout_backoff_seed_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(30L)));
    ik = a.a("finsky.scheduler.job_scheduler_timeout_backoff_kill_switch", localBoolean2);
    iq = a.a("finsky.scheduler.max_job_scheduler_timeout_backoff_ms", Long.valueOf(TimeUnit.HOURS.toMillis(5L)));
    hX = a.a("finsky.scheduler.max_alarm_manager_timeout_backoff_seed_ms", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    it = a.a("finsky.scheduler.real_network_recheck_backoff_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(60L)));
    cZ = a.a("finsky.entrypoint.timeout_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(15L)));
    iX = a.a("finsky:wh:showAiaNoticeOnTosMinOsVersion", localInteger4);
    j = a.a("finsky:wh:aiaTosOptInTaskApiClientConnectTimeoutMs", Long.valueOf(TimeUnit.SECONDS.toMillis(5L)));
    i = a.a("finsky:wh:aiaTosOptInTaskApiClientCallTimeoutMs", Long.valueOf(TimeUnit.SECONDS.toMillis(3L)));
    iW = a.a("finsky:wh:showAiaNoticeOnTosMinGmsCoreContainerVersion", Integer.valueOf(11021000));
    iV = a.a("finsky:wh:showAiaNoticeLearnMoreUrl", "https://support.google.com/googleplay/?p=instant_apps_tos");
    bn = a.a("finsky.db.max_audit_row_count", Long.valueOf(100L));
    fg = a.a("finsky.max_apps_returned_for_getPackagesForDevice_v1", Integer.valueOf(460));
    bv = a.a("finsky.nav_drawer.delay_configuration_time_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(10L)));
    a.a("finsky._test_install_split_apks_enabled", localBoolean2);
    fL = a.a("finsky.my_apps_url_default", "myApps");
    fP = a.a("finsky.subscription_explore_button_url", "https://play.google.com/store/apps/editorial_collection/promotion_topic_30031d8_subs_center_topicpage");
    gF = a.a("finsky.pgs_endpoint", "playgateway-pa.googleapis.com:443");
    kk = a.a("finsky.verify_apps_logging.enabled", localBoolean2);
    ex = a.a("finsky.install_holdoff_kill_switch", localBoolean2);
    eA = a.a("finsky.install_holdoff_recovery_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(5L)));
    ji = a.a("finsky.status_code_kill_switch", localBoolean2);
    eB = a.a("finsky.install_holdoff_timeout_millis", Long.valueOf(TimeUnit.HOURS.toMillis(1L)));
    ey = a.a("finsky.install_holdoff_rate_limiter_max_calls", Integer.valueOf(6));
    ez = a.a("finsky.install_holdoff_rate_limiter_time_period_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    eC = a.a("finsky.install_ignored_due_to_policy_enabled", localBoolean1);
    eZ = a.a("finsky.log_install_session_ids_kill_switch.enabled", localBoolean2);
    aQ = a.b("market_client_id", "am-google");
    co = a.a("finsky.enable_chrome_on_managed_profile_on_o", localBoolean1);
    ba = a.a("finsky.critical_low_storage_card_threshold_bytes", localLong1);
    ix = a.a("finsky.self_update_download_recovery_kill_switch", localBoolean2);
    jc = a.a("finsky.sim_switch_whitelisted_carriers", "");
    ga = a.a("finsky.notification_store_max_days_old", Integer.valueOf(60));
    gb = a.a("finsky.notification_store_max_notifications", localInteger7);
    jF = a.a("finsky.upload_extra_device_configuration", localBoolean1);
    W = a.a("finsky.assist_card_request_factory_timeout_ms", Long.valueOf(TimeUnit.HOURS.toMillis(24L)));
    a.a("finsky.shortcut_badger_incompatible_apps", "com.excelliance.multiaccount,com.excelliance.multiaccounts");
    iR = a.a("finsky.shortcut_badger_incompatible_app_substrings", "excelliance");
    aW = a.a("finsky.content_sync_scheduler_settle_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(15L)));
    aV = a.a("finsky.content_sync_scheduler_retry_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(20L)));
    aU = a.a("finsky.content_sync_scheduler_max_num_retries", localInteger3);
    jo = a.a("finsky.temp_files_expire_ms", Long.valueOf(TimeUnit.DAYS.toMillis(2L)));
    Y = a.a("finsky.auto_install_dependencies_whitelist", "com.google.ar.core");
    fV = a.a("finsky.no_connection_snackbar_display_duration_millis", localInteger10);
    fT = a.a("finsky.no_connection_notification_expiry_millis", Long.valueOf(TimeUnit.DAYS.toMillis(30L)));
    fU = a.a("finsky.no_connection_snackbar_dismiss_timeout_duration_millis", Integer.valueOf(25000));
    aL = a.a("finsky.cdp_saved_animation_duration_millis", localInteger9);
    aK = a.a("finsky.cdp_saved_animation_delay_millis", Integer.valueOf(250));
    fK = a.a("finsky.my_apps_updates_card_type_refresh_time_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(2L)));
    hL = a.a("finsky.review_policy_url", "https://play.google.com/about/comment-posting-policy.html");
    dT = a.a("finsky.google_maps_query_url", "https://www.google.com/maps/search/?api=1&query=%s");
    n = a.a("finsky.allow_p2p_install_when_safetynet_result_unavailable", localBoolean2);
    hU = a.a("finsky.scheduled_acquisition_maximum_attempt", localInteger2);
    hV = a.a("finsky.scheduled_acquisition_scheduler_delay_ms", Long.valueOf(TimeUnit.SECONDS.toMillis(15L)));
    V = a.a("finsky.art.profiles_upload.window_end_delay_s", Long.valueOf(TimeUnit.HOURS.toSeconds(23L)));
    U = a.a("finsky.art.profiles_upload.max_daily_upload_bytes", Integer.valueOf((int)at.d.a(1L)));
    fn = a.a("finsky:wh:maxTimesToShowTryNowTooltip", localInteger1);
    aO = a.a("finsky.notification.clear_cache_and_experiments", localBoolean1);
    ds = a.a("finsky.filter_installed_apps_by_default", localBoolean1);
    cY = a.a("finsky.enterprise_managed_device_account_restriction", localBoolean1);
    cW = a.a("finsky.enterprise_daily_hygiene_holdoff_enabled", localBoolean2);
    cX = a.a("finsky.enterprise_daily_hygiene_holdoff_setup_delay_ms", Long.valueOf(TimeUnit.MINUTES.toMillis(1L)));
    eP = a.a("finsky.passive_state_management_killswitch", localBoolean2);
    du = a.a("finsky.flexible_self_update.is_enabled", localBoolean1);
    dv = a.a("finsky.flexible_self_update.lifecycle_step", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    dw = a.a("finsky.flexible_self_update.maximum_delay_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    dz = a.a("finsky.flexible_self_update.maximum_require_wifi_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    dy = a.a("finsky.flexible_self_update.maximum_require_idle_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    dx = a.a("finsky.flexible_self_update.maximum_require_charging_ms", Long.valueOf(TimeUnit.DAYS.toMillis(1L)));
    bE = a.a("finsky.device_settings_cache.ttl_ms", Long.valueOf(TimeUnit.DAYS.toMillis(3L)));
    aj = a.a("finsky.base_url_provider_force_legacy_url", localBoolean2);
    ak = a.a("finsky.base_url_provider_use_tokenized_url_kill_switch", localBoolean2);
    al = a.a("finsky.base_url_provider_use_zero_rating_kill_switch", localBoolean2);
    a.a("finsky.base_url_provider_headless_kill_switch", localBoolean2);
    lA = a.a("finsky.zero_rating_base_url", "https://play-ti.googleapis.com/fdfe/");
    a.a("finsky.headless_base_url", "https://services.googleapis.cn/fdfe/");
    he = a.a("finsky.play_tokenized_base_url", "https://play-tokenized.googleapis.com/fdfe/");
    dh = a.a("finsky.debug.fast_logs_flushing_upload_delay_ms", localLong1);
    lB = a.a("finsky.zero_rating_cpid_override", "");
    lC = a.a("finsky.zero_rating_data_plan_identifier_whitelist_for_test", "");
    lD = a.a("finsky.zero_rating_gtaf_fetcher_timeout_seconds", Long.valueOf(20L));
  }
  
  public static a a()
  {
    if (lE == null) {}
    for (;;)
    {
      a locala = a.a("android_id", Long.valueOf(0L));
      lE = locala;
      if (((Long)locala.b()).longValue() == 0L) {
        FinskyLog.d("Unexpected android-id = 0", new Object[0]);
      }
      do
      {
        return lE;
      } while (((Long)lE.b()).longValue() != 0L);
    }
  }
}


/* Location:              /home/chengjian/CM_test/gp/apk/a.jar!/com/google/android/finsky/ag/d.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */